
<div id="sidebar"> <a href="#" class="visible-phone"><i class="icon icon-list"></i> Menu</a>
    <ul>


        <li class=""><a href=""><i class="icon icon-home"></i> <span>Dashboard</span></a></li>

        <li class="active"><a href="<?= base_url('') ?>/clientes"><i class="icon icon-group"></i> <span>Clientes</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/produtos"><i class="icon icon-barcode"></i> <span>Produtos</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/servicos"><i class="icon icon-wrench"></i> <span>Serviços</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/os"><i class="icon icon-tags"></i> <span>Ordens de Serviço</span></a></li>

        

        
        <li class="submenu ">
            <a href="#"><i class="icon icon-money"></i> <span>Financeiro</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="<?= base_url('')?>/financeiro/lancamentos"">Lançamentos</a></li>                
            </ul>
        </li>


        


        <li class="submenu ">
            <a href="#"><i class="icon icon-cog"></i> <span>Configurações</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="/./LayoutFabrica/configuracoes/usuarios">Usuários</a></li>
                <li><a href="/./LayoutFabrica/configuracoes/emitente">Emitente</a></li>
                <!--<li><a href="index.php/permissoes">Permissões</a></li>-->
                <!--<li><a href="index.php/mapos/backup">Backup</a></li>-->
                <!-- <li><a  href="#" title="configuraremail" onClick="abrirnotificacao(this)">Email(imap)</a></li>-->
                <li><a  href="#" title="configurarpagseguro.php" onClick="abrirnotificacao(this)">PagSeguro</a></li>
            </ul>
        </li>


    </ul>
</div>
<div id="content">
    <div id="content-header">
        <div id="breadcrumb"> <a href="" title="Dashboard" class="tip-bottom"><i class="icon-home"></i> Dashboard</a> <a href="<?= base_url('')?>/clientes" class="tip-bottom" title="Clientes">Clientes</a> </a> </div>
    </div>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="span12">
                    <div class="container-fluid col-sm-5  nopadding" style="margin-left: 3%;">
                        <?php
                        $this->alerta();
                        ?>
                    </div>

                    <a href="<?= base_url('') ?>/clientes/adicionar" class="btn btn-success"><i class="icon-plus icon-white"></i> Adicionar Cliente</a>    


                    <div class="widget-box">
                        <div class="widget-title">
                            <span class="icon">
                                <i class="icon-user"></i>
                            </span>
                            <h5>Clientes</h5>
                        </div>
                        <div class="widget-content nopadding">
                            <table class="table table-bordered ">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Nome</th>
                                        <th>CPF/CNPJ</th>
                                        <th>Telefone</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <?php
                                $total = 0;
                                foreach ($this->view->clientes as $linha) {
                                    $id = count($linha['idClientes']);
                                    $total = $total + $id;
                                }
                                if ($total > 0) {
                                    ?>
                                    <tbody>
                                        <?php foreach ($this->view->clientes as $linha) { ?>
                                            <tr>
                                                <td><?php echo $linha['idClientes'] ?></td>
                                                <td><?php echo $linha['nomeCliente'] ?></td>
                                                <td><?php echo $linha['documento'] ?></td>
                                                <td><?php echo $linha['celular'] ?></td>
                                            </tr>
                                            <tr>
                                                <td colspan="4">
                                                    <a href="<?= base_url('') ?>/clientes/visualizar?id=<?= $linha['idClientes'] ?>" style="margin-right: 1%" class="btn tip-top" title="Ver mais detalhes"><i class="icon-eye-open"></i></a>
                                                    <a href="<?= base_url('') ?>/clientes/editar?id=<?= $linha['idClientes'] ?>" style="margin-right: 1%" class="btn btn-info tip-top" title="Editar Cliente"><i class="icon-pencil icon-white"></i></a>
                                                    <a href="#modal-excluir" role="button" data-toggle="modal" cliente="80" style="margin-right: 1%" class="btn btn-danger tip-top" title="Excluir Cliente"><i class="icon-remove icon-white"></i></a>
                                                </td>
                                            </tr>
                                            <tr>

                                                <!-- Modal  Excluir Cliente-->
                                        <div id="modal-excluir" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="width:76%; max-width:400px;">
                                            <form action="<?= base_url('') ?>/clientes/remover?id=<?= $linha['idClientes'] ?>" method="post" >
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                    <h5 id="myModalLabel">Excluir Cliente</h5>
                                                </div>
                                                <div class="modal-body">                                                    
                                                    <h5 style="text-align: center">Deseja realmente excluir este cliente e os dados associados a ele (OS, Vendas, Receitas)?</h5>
                                                </div>
                                                <div class="modal-footer">
                                                    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
                                                    <button class="btn btn-danger">Excluir</button>
                                                </div>
                                            </form>
                                        </div>
                                    <?php } ?>

                                    </tr>
                                    </tbody>
                                    <?php
                                } else {
                                    ?>
                                    <tbody>
                                        <tr>
                                            <td colspan = "5">Nenhum Cliente Cadastrado</td>
                                        </tr>
                                    </tbody>
                                    <?php
                                }
                                ?>
                            </table>
                        </div>
                    </div>












                    <script type="text/javascript">
                        $(document).ready(function () {


                            $(document).on('click', 'a', function (event) {

                                var cliente = $(this).attr('cliente');
                                $('#idCliente').val(cliente);

                            });

                        });

                    </script>


                </div>
            </div>
        </div>
    </div>
</div>

