
<div id="sidebar"> <a href="#" class="visible-phone"><i class="icon icon-list"></i> Menu</a>
    <ul>


        <li class=""><a href=""><i class="icon icon-home"></i> <span>Dashboard</span></a></li>

        <li class="active"><a href="<?= base_url('') ?>/clientes"><i class="icon icon-group"></i> <span>Clientes</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/produtos"><i class="icon icon-barcode"></i> <span>Produtos</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/servicos"><i class="icon icon-wrench"></i> <span>Serviços</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/os"><i class="icon icon-tags"></i> <span>Ordens de Serviço</span></a></li>

        

        <li class="submenu ">
            <a href="#"><i class="icon icon-money"></i> <span>Financeiro</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="<?= base_url('')?>/financeiro/lancamentos">Lançamentos</a></li>                
            </ul>
        </li>


        


<!--        <li class="submenu ">
            <a href="#"><i class="icon icon-cog"></i> <span>Configurações</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="/./LayoutFabrica/configuracoes/usuarios">Usuários</a></li>
                <li><a href="/./LayoutFabrica/configuracoes/emitente">Emitente</a></li>
                <li><a href="index.php/permissoes">Permissões</a></li>
                <li><a href="index.php/mapos/backup">Backup</a></li>
                 <li><a  href="#" title="configuraremail" onClick="abrirnotificacao(this)">Email(imap)</a></li>
                <li><a  href="#" title="configurarpagseguro.php" onClick="abrirnotificacao(this)">PagSeguro</a></li>
            </ul>
        </li>-->


    </ul>
</div>

<div id="content">
    <div id="content-header">
        <?= $this->AlertaHome();?> 
        <div id="breadcrumb"> <a href="<?= base_url('')?>" title="Dashboard" class="tip-bottom"><i class="icon-home"></i> Dashboard</a> <a href="<?= base_url('')?>/clientes" class="tip-bottom" title="Clientes">Clientes</a> <a href="<?= base_url('')?>/clientes/editar" class="current tip-bottom" title="Editar">Editar</a> </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="container-fluid col-sm-5  nopadding" style="margin-left: 3%;">
                
                </div>

                <div class="row-fluid" style="margin-top:0">
                    <div class="span12">
                        <div class="widget-box">
                            <div class="widget-title">
                                <span class="icon">
                                    <i class="icon-user"></i>
                                </span>
                                <h5>Editar Cliente</h5>
                            </div>
                            <div class="widget-content nopadding">
                                <form action="<?= base_url('')?>/clientes/editar/salvar" id="formCliente" method="post" class="form-horizontal" >
                                    <div class="control-group">
                                        <?php foreach ($this->view->oneClientes as $clientes){?>
                                        <input type="hidden" name="idClientes" value="<?=$clientes['idClientes']?>" />
                                        
                                        <label for="nomeCliente" class="control-label">Nome<span class="required">*</span></label>
                                        <div class="controls">
                                            <input id="nomeCliente" type="text" name="nomeCliente" value="<?=$clientes['nomeCliente']?>"  />
                                        </div>
                                    </div>                                    
                <div class="control-group">
    			<label>&nbsp;</label>
                        <div class="controls">
    			<input type="radio" value="cpf" name="documento" checked="checked"> CPF
    			<input type="radio" value="cnpj" name="documento"> CNPJ
                        </div>
    		</div>
                <div class="control-group">                    
               <div id="cpf">
                   <label for="documentoCPF" class="control-label">CPF <span>*</span></label><br>
                   <div class="controls">
                       <input type="text" name="documentoCpf" id="documentoCPF" class="cpf required" value="<?php if(strlen($clientes['documento']) === 14){echo $clientes['documento'];}?>" maxlength="15">
                   </div>
    		</div>
                </div>
                <div class="control-group">                    
                <div id="cnpj" style="display: none;">
    			<label for="documentoCNPJ" class="control-label">CNPJ <span>*</span></label>
                        <div class="controls">
                            <input type="text" name="documentoCpnj" id="documentoCNPJ" class="cnpj" value="<?php if(strlen ($clientes['documento']) === 18){echo $clientes['documento'];}?>" maxlength="18">
                        </div>
    		</div>
                </div>
                                    <div class="control-group">
                                        <label for="telefone" class="control-label">Telefone<span class="required">*</span></label>
                                        <div class="controls">
                                            
                                            <input id="telefone" type="text" name="telefone" value="<?=$clientes['telefone']?>"  />
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label for="celular" class="control-label">Celular</label>
                                        <div class="controls">
                                            <input id="celular" type="text" name="celular" value="<?=$clientes['celular']?>"  />
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label for="email" class="control-label">Email<span>*</span></span></label>
                                        <div class="controls">
                                            <input id="email" type="text" name="email" value="<?=$clientes['email']?>"  />
                                        </div>
                                    </div>

                                    <div class="control-group" class="control-label">
                                        <label for="rua" class="control-label">Rua<span class="required">*</span></label>
                                        <div class="controls">
                                            <input id="rua" type="text" name="rua" value="<?=$clientes['rua']?>"  />
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label for="numero" class="control-label">Número<span class="required">*</span></label>
                                        <div class="controls">
                                            <input id="numero" type="text" name="numero" value="<?=$clientes['numero']?>"  />
                                        </div>
                                    </div>

                                    <div class="control-group" class="control-label">
                                        <label for="bairro" class="control-label">Bairro<span class="required">*</span></label>
                                        <div class="controls">
                                            <input id="bairro" type="text" name="bairro" value="<?=$clientes['bairro']?>"  />
                                        </div>
                                    </div>

                                    <div class="control-group" class="control-label">
                                        <label for="cidade" class="control-label">Cidade<span class="required">*</span></label>
                                        <div class="controls">
                                            <input id="cidade" type="text" name="cidade" value="<?=$clientes['cidade']?>"  />
                                        </div>
                                    </div>

                                    <div class="control-group" class="control-label">
                                        <label for="estado" class="control-label">Estado<span class="required">*</span></label>
                                        <div class="controls">
                                            <input id="estado" type="text" name="estado" value="<?=$clientes['estado']?>"  />
                                        </div>
                                    </div>

                                    <div class="control-group" class="control-label">
                                        <label for="cep" class="control-label">CEP<span class="required">*</span></label>
                                        <div class="controls">
                                            <input id="cep" type="text" name="cep" value="<?=$clientes['cep']?>"  />
                                        </div>
                                    </div>
                                        <?php }?>


                                    <div class="form-actions">
                                        <div class="span12">
                                            <div class="span6 offset3">
                                                <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Alterar</button>
                                                <a href="https://www.ultramapos.online/index.php/clientes" id="" class="btn"><i class="icon-arrow-left"></i> Voltar</a>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>



                <script src="https://www.ultramapos.online/js/jquery.validate.js"></script>
                <script>
    jQuery("input[name=documento]:radio").change(
    	function(){
    		if( jQuery("input[name=documento]:radio:checked").val() == 'cpf' )
    		{
    			jQuery("#cnpj").hide();
    			jQuery("#documentoCNPJ").removeClass('required');
    			jQuery("#cpf").show();
    			jQuery("#documentoCPF").addClass('required');
    		}
    		else
    		{
    			jQuery("#cnpj").show();
    			jQuery("#documentoCNPJ").addClass('required');
    			jQuery("#cpf").hide();
    			jQuery("#documentoCPF").removeClass('required');
    		}
    	}	
    );
    </script>
                <script type="text/javascript">
                     $(document).ready(function () {
                         //Mascara para os inpust70645-160
        
        $("#celular").mask("(00) 0 0000-0000");
        $("#telefone").mask("(00) 0000-0000");
        $("#documentoCNPJ").mask("99.999.999/9999-99");
        $("#documentoCPF").mask("999.999.999-99");
        $("#cep").mask("99999-999");
                         
                         $('#formCliente').validate({
                             rules: {
                                 nomeCliente: {required: true},
                                 //  documento:{ required: true},
                                 telefone: {required: true},
                                 //  email:{ required: true},
                                 rua: {required: true},
                                 numero: {required: true},
                                 bairro: {required: true},
                                 cidade: {required: true},
                                 estado: {required: true},
                                 cep: {required: true}
                             },
                             messages: {
                                 nomeCliente: {required: 'Campo Requerido.'},
                                 //    documento :{ required: 'Campo Requerido.'},
                                 telefone: {required: 'Campo Requerido.'},
                                 //   email:{ required: 'Campo Requerido.'},
                                 rua: {required: 'Campo Requerido.'},
                                 numero: {required: 'Campo Requerido.'},
                                 bairro: {required: 'Campo Requerido.'},
                                 cidade: {required: 'Campo Requerido.'},
                                 estado: {required: 'Campo Requerido.'},
                                 cep: {required: 'Campo Requerido.'}

                             },

                             errorClass: "help-inline",
                             errorElement: "span",
                             highlight: function (element, errorClass, validClass) {
                                 $(element).parents('.control-group').addClass('error');
                             },
                             unhighlight: function (element, errorClass, validClass) {
                                 $(element).parents('.control-group').removeClass('error');
                                 $(element).parents('.control-group').addClass('success');
                             }
                         });
                     });
                </script>



            </div>
        </div>
    </div>
</div>