
<div id="sidebar"> <a href="#" class="visible-phone"><i class="icon icon-list"></i> Menu</a>
    <ul>


        <li class=""><a href=""><i class="icon icon-home"></i> <span>Dashboard</span></a></li>

        <li class="active"><a href="<?= base_url('') ?>/clientes"><i class="icon icon-group"></i> <span>Clientes</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/produtos"><i class="icon icon-barcode"></i> <span>Produtos</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/servicos"><i class="icon icon-wrench"></i> <span>Serviços</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/os"><i class="icon icon-tags"></i> <span>Ordens de Serviço</span></a></li>



        <li class="submenu ">
            <a href="#"><i class="icon icon-money"></i> <span>Financeiro</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="<?= base_url('') ?>/financeiro/lancamentos">Lançamentos</a></li>

            </ul>
        </li>





<!--        <li class="submenu ">
            <a href="#"><i class="icon icon-cog"></i> <span>Configurações</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="/./LayoutFabrica/configuracoes/usuarios">Usuários</a></li>
                <li><a href="/./LayoutFabrica/configuracoes/emitente">Emitente</a></li>
                <li><a href="index.php/permissoes">Permissões</a></li>
                <li><a href="index.php/mapos/backup">Backup</a></li>
                 <li><a  href="#" title="configuraremail" onClick="abrirnotificacao(this)">Email(imap)</a></li>
                <li><a  href="#" title="configurarpagseguro.php" onClick="abrirnotificacao(this)">PagSeguro</a></li>
            </ul>
        </li>-->


    </ul>
</div>

<div id="content">
    <div id="content-header">
        <div id="breadcrumb"> <a href="<?= base_url('') ?>" title="Dashboard" class="tip-bottom"><i class="icon-home"></i> Dashboard</a> <a href="<?= base_url('') ?>/clientes" class="tip-bottom" title="Clientes">Clientes</a> <a href="<?= base_url('') ?>/clientes/visualizar" class="current tip-bottom" title="Visualizar">Visualizar</a> </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="widget-box">
                    <div class="widget-title">
                        <ul class="nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#tab1">Dados do Cliente</a></li>

                            <div class="buttons">
                                <a title="Icon Title" class="btn btn-mini btn-info" href="<?= base_url('') ?>/clientes/editar?id=81"><i class="icon-pencil icon-white"></i> Editar</a>                    
                            </div>
                        </ul>
                    </div>
                    <div class="widget-content tab-content">
                        <div id="tab1" class="tab-pane active" style="min-height: 300px">

                            <div class="accordion" id="collapse-group">
                                <div class="accordion-group widget-box">
                                    <div class="accordion-heading">
                                        <div class="widget-title">
                                            <a data-parent="#collapse-group" href="#collapseGOne" data-toggle="collapse">
                                                <span class="icon"><i class="icon-list"></i></span><h5>Dados Pessoais</h5>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="collapse in accordion-body" id="collapseGOne">
                                        <div class="widget-content">
                                            <table class="table table-bordered">
                                                <tbody>
                                                    <?php foreach (@$this->view->oneClientes as $cliente) { ?>
                                                        <tr>
                                                            <td style="text-align: right; width: 30%"><strong>Nome</strong></td>
                                                            <td><?= $cliente['nomeCliente'] ?></td>
                                                        </tr>
                                                        <tr>
                                                            <td style="text-align: right"><strong>Documento</strong></td>
                                                            <td><?= $cliente['documento'] ?></td>
                                                        </tr>
                                                        <tr>
                                                            <td style="text-align: right"><strong>Data de Cadastro</strong></td>
                                                            <td><?= date('d/m/Y', strtotime($cliente['dataCadastro'])) ?></td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="accordion-group widget-box">
                                        <div class="accordion-heading">
                                            <div class="widget-title">
                                                <a data-parent="#collapse-group" href="#collapseGTwo" data-toggle="collapse">
                                                    <span class="icon"><i class="icon-list"></i></span><h5>Contatos</h5>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="collapse accordion-body" id="collapseGTwo">
                                            <div class="widget-content">
                                                <table class="table table-bordered">
                                                    <tbody>
                                                        <tr>
                                                            <td style="text-align: right; width: 30%"><strong>Telefone</strong></td>
                                                            <td><?= $cliente['telefone'] ?></td>
                                                        </tr>
                                                        <tr>
                                                            <td style="text-align: right"><strong>Celular</strong></td>
                                                            <td><?= $cliente['celular'] ?></td>
                                                        </tr>
                                                        <tr>
                                                            <td style="text-align: right"><strong>Email</strong></td>
                                                            <td><?= $cliente['email'] ?></td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="accordion-group widget-box">
                                        <div class="accordion-heading">
                                            <div class="widget-title">
                                                <a data-parent="#collapse-group" href="#collapseGThree" data-toggle="collapse">
                                                    <span class="icon"><i class="icon-list"></i></span><h5>Endereço</h5>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="collapse accordion-body" id="collapseGThree">
                                            <div class="widget-content">
                                                <table class="table table-bordered">
                                                    <tbody>
                                                        <tr>
                                                            <td style="text-align: right; width: 30%"><strong>Rua</strong></td>
                                                            <td><?= $cliente['rua'] ?></td>
                                                        </tr>
                                                        <tr>
                                                            <td style="text-align: right"><strong>Número</strong></td>
                                                            <td><?= $cliente['numero'] ?></td>
                                                        </tr>
                                                        <tr>
                                                            <td style="text-align: right"><strong>Bairro</strong></td>
                                                            <td><?= $cliente['bairro'] ?></td>
                                                        </tr>
                                                        <tr>
                                                            <td style="text-align: right"><strong>Cidade</strong></td>
                                                            <td><?= $cliente['cidade'] ?></td>
                                                        </tr>
                                                        <tr>
                                                            <td style="text-align: right"><strong>CEP</strong></td>
                                                            <td><?= $cliente['cep'] ?></td>

                                                        </tr>
                                                    <?php } ?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

