
<div id="sidebar"> <a href="#" class="visible-phone"><i class="icon icon-list"></i> Menu</a>
    <ul>


        <li class=""><a href=""><i class="icon icon-home"></i> <span>Dashboard</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/clientes"><i class="icon icon-group"></i> <span>Clientes</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/produtos"><i class="icon icon-barcode"></i> <span>Produtos</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/servicos"><i class="icon icon-wrench"></i> <span>Serviços</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/os"><i class="icon icon-tags"></i> <span>Ordens de Serviço</span></a></li>

        <li class="submenu active">
            <a href="#"><i class="icon icon-money"></i> <span>Financeiro</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="<?= base_url('') ?>/financeiro/lancamentos">Lançamentos</a></li>                
            </ul>
        </li>
    </ul>
</div>

<div id="content">
    <div id="content-header">
        <div id="breadcrumb"> <a href="<?= base_url('') ?>/dashboard" title="Dashboard" class="tip-bottom"><i class="icon-home"></i> Dashboard</a> <a href="<?= base_url('') ?>/financeiro/lancamentos" class="tip-bottom" title="Financeiro">Financeiro</a> <a href="<?= base_url('') ?>/financeiro/lancamentos" class="current tip-bottom" title="Lancamentos">Editar Lancamentos</a> </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">


                <div class="container-fluid col-sm-5  nopadding" style="margin-left: 3%;">
                    <?php
                    $this->alertaHome();
                    ?>
                </div>

                <div class="row-fluid" style="margin-top:0">
                    <div class="span12">
                        <div class="widget-box">
                            <div class="widget-title">
                                <span class="icon">
                                    <i class="icon-user"></i>
                                </span>
                                <h5>Editar Lançamentos</h5>
                            </div>
                            <div class="widget-content nopadding">
                                <form id="formEditar" action="<?= base_url('') ?>/financeiro/lancamentos/editar/salvar" method="post">

                                    <?php foreach ($this->view->oneLancamentEdit as $lancamentos) {
                                        ?> 
                                        <div class="form-control" style="height: 380px;">
                                            <div class="col-sm-12 alert alert-info" > Obrigatório o preenchimento dos campos com asterisco.</div>

                                            <div class="col-sm-12">
                                                <div class="form-group">
                                                    <label for="descricao">Descrição</label>
                                                    <input class="form-control" id="descricaoEditar" type="text" name="descricao" value="<?= $lancamentos['descricao'] ?>"  />
                                                    <input id="idLancamentos" type="hidden" name="idLancamentos" value="<?= $lancamentos['idLancamentos'] ?>"  />
                                                </div>  
                                                <div class="form-group">
                                                    <label for="fornecedor">Fornecedor / Empresa*</label>
                                                    <input class="form-control" id="fornecedorEditar" type="text" name="fornecedor" value="<?= $lancamentos['cliente_fornecedor'] ?>" />
                                                </div>


                                                <div class="form-group col-sm-4" style="padding-left: 0px;">

                                                    <label for="valor">Valor*</label>
                                                    <input type="hidden" class="form-control" name="tipo" value="despesa" />  
                                                    <input type="hidden" class="form-control" id="idEditar" name="id" value="" /> 
                                                    <input class="form-control money"  type="text" name="valor" id="valorEditar" value=" <?= $lancamentos['valor'] ?>"/>
                                                </div>

                                                <div class="col-sm-4">
                                                    <label for="vencimento">Data Vencimento*</label>
                                                    <input class="form-control"  type="date" name="vencimento" id="vencimentoEditar" value="<?= $lancamentos['data_vencimento'] ?>" />
                                                </div>
                                                <div class="form-group col-sm-4" style="padding-right: 0px;">
                                                    <label for="vencimento">Tipo*</label>
                                                    <select class="form-control" name="tipo" id="tipoEditar" >
                                                        <option value="Receita">Receita</option>
                                                        <option value="Despesa">Despesa</option>
                                                    </select>
                                                </div>
                                                <div class="form-group">

                                                    <div class="col-sm-12" style="padding-left: 0px;">

                                                        <div class="form-check" style="">
                                                            <input class="form-check-input" type="checkbox" id="clicaPagamento" name="pago" value="Sim">
                                                            <label class="form-check-label" for="gridCheck1">
                                                                Foi Pago?
                                                            </label>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-sm-12" style="padding-left: 0px;" id="pagamento"> 
                                                    <div class="form-group col-sm-4" style="padding-left: 0px;">
                                                        <label for="pagamento">Data Pagamento</label>
                                                        <input class="form-control datepicker"  id="pagamentoEditar" type="date"  name="dataPagamento" />  
                                                    </div>                                            
                                                    <div class=" form-group col-sm-4">    
                                                        <label for="formaPgto">Forma Pgto</label>
                                                        <select name="formaPgto" id="formaPgtoEditar"  class="form-control">
                                                            <option value="">-</option>
                                                            <option value="Dinheiro">Dinheiro</option>
                                                            <option value="Cartão de Crédito">Cartão de Crédito</option>
                                                            <option value="Cheque">Cheque</option>
                                                            <option value="Boleto">Boleto</option>
                                                            <option value="Depósito">Depósito</option>
                                                            <option value="Débito">Débito</option>        
                                                        </select>
                                                    </div>
                                                </div>

                                                <?php
                                            }
                                            ?>
                                            <div class="col-sm-12">
                                                <div class="text-right">
                                                    <a href="<?= base_url('') ?>/financeiro/lancamentos" class="btn btn-danger">Cancelar</a>
                                                    <button class="btn btn-primary">Salvar Alterações</button>
                                                </div>
                                            </div>
                                                 </div>
                                            </form>
                                        </div>
                                   
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




<script type="text/javascript">
    $(document).ready(function () {
        $("#pagamento").hide();
        $("#clicaPagamento").click("change", function () {
            $("#pagamento").toggle();
        });
        $(".money").maskMoney({
            prefix: "R$:",
            decimal: ",",
            thousands: "."
        });
    });
</script>
<script>
//$(document).ready(function(){
//    //$("#valor").maskMoney({prefix:'R$ ', allowNegative: true, thousands:'.', decimal:',', affixesStay: false});
//});
</script>