
<div id="sidebar"> <a href="#" class="visible-phone"><i class="icon icon-list"></i> Menu</a>
    <ul>


        <li class="active"><a href=""><i class="icon icon-home"></i> <span>Dashboard</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/clientes"><i class="icon icon-group"></i> <span>Clientes</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/produtos"><i class="icon icon-barcode"></i> <span>Produtos</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/servicos"><i class="icon icon-wrench"></i> <span>Serviços</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/os"><i class="icon icon-tags"></i> <span>Ordens de Serviço</span></a></li>


        <li class="submenu ">
            <a href="#"><i class="icon icon-money"></i> <span>Financeiro</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="<?= base_url('') ?>/financeiro/lancamentos">Lançamentos</a></li>             
            </ul>
        </li>
    </ul>
</div>
<div id="content">

    <div id="content-header">        
        <?= $this->AlertaHome(); ?>        
        <div id="breadcrumb"> <a href="<?= base_url('') ?>/dashboard" title="Dashboard" class="tip-bottom"><i class="icon-home"></i> Dashboard</a> </div>
    </div>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <!--Action boxes-->
                <div class="container-fluid">

                    <div class="quick-actions_homepage">
                        <ul class="quick-actions">

                            <li class="bg_lb btn btn-outline-primary"> <a href="<?= base_url('') ?>/clientes"> <i class="icon-group"></i> Clientes</a> </li>
                            <li class="bg_lg btn btn-outline-success"> <a href="<?= base_url('') ?>/produtos"> <i class="icon-barcode"></i> Produtos</a> </li>
                            <li class="bg_ly btn btn-outline-warning"> <a href="<?= base_url('') ?>/servicos"> <i class="icon-wrench"></i> Serviços</a> </li>
                            <li class="bg_lo btn btn-outline-danger"> <a href="<?= base_url('') ?>/os"> <i class="icon-tags"></i> OS</a> </li>
                            <li class="bg_ls btn btn-outline-info"> <a href="<?= base_url('') ?>/financeiro/lancamentos"><i class="icon-shopping-cart"></i>Financeiro</a></li>                            
                        </ul>
                    </div>
                    <div class="col-md-12">
                        <div class="row">
                            <div style="width:75%;">
                                <canvas id="canvas"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>




    window.chartColors = {
        red: 'rgb(255, 99, 132)',
        orange: 'rgb(255, 159, 64)',
        yellow: 'rgb(255, 205, 86)',
        green: 'rgb(75, 192, 192)',
        blue: 'rgb(54, 162, 235)',
        purple: 'rgb(153, 102, 255)',
        grey: 'rgb(201, 203, 207)'
    };




   $.getJSON("http://localhost:8080/estatistica/JSON/receita", (data) => {
        var label = data.mes;
        console.log(label);
    });
    

    var MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    var config = {
        type: 'line',

        data: {
            labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
            datasets: [{
                    label: 'Despesas',
                    backgroundColor: window.chartColors.red,
                    borderColor: window.chartColors.red,
                    data: [
                        21, 2, 14, 20, 200, 100, 50
                    ],
                    fill: false,
                }, {
                    label: 'Receitas',
                    fill: false,
                    backgroundColor: window.chartColors.blue,
                    borderColor: window.chartColors.blue,
                    data: [
                        200,
                        50,
                        14,
                        300,
                        10,
                        20,
                        10
                    ],
                }]
        },
        options: {
            responsive: true,
            title: {
                display: true,
                text: 'Estatistica Financeira'
            },
            tooltips: {
                mode: 'index',
                intersect: false,
            },
            hover: {
                mode: 'nearest',
                intersect: true
            },
            scales: {
                xAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Meses'
                        }
                    }],
                yAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Valores R$:'
                        }
                    }]
            }
        }
    };

    window.onload = function () {
        var ctx = document.getElementById('canvas').getContext('2d');
        window.myLine = new Chart(ctx, config);
    };




//		var colorNames = Object.keys(window.chartColors);
//		document.getElementById('addDataset').addEventListener('click', function() {
//			var colorName = colorNames[config.data.datasets.length % colorNames.length];
//			var newColor = window.chartColors[colorName];
//			var newDataset = {
//				label: 'Dataset ' + config.data.datasets.length,
//				backgroundColor: newColor,
//				borderColor: newColor,
//				data: [],
//				fill: false
//			};
//
//			for (var index = 0; index < config.data.labels.length; ++index) {
//				newDataset.data.push(randomScalingFactor());
//			}
//
//			config.data.datasets.push(newDataset);
//			window.myLine.update();
//		});
//
//		document.getElementById('addData').addEventListener('click', function() {
//			if (config.data.datasets.length > 0) {
//				var month = MONTHS[config.data.labels.length % MONTHS.length];
//				config.data.labels.push(month);
//
//				config.data.datasets.forEach(function(dataset) {
//					dataset.data.push(randomScalingFactor());
//				});
//
//				window.myLine.update();
//			}
//		});
//
//		document.getElementById('removeDataset').addEventListener('click', function() {
//			config.data.datasets.splice(0, 1);
//			window.myLine.update();
//		});
//
//		document.getElementById('removeData').addEventListener('click', function() {
//			config.data.labels.splice(-1, 1); // remove the label first
//
//			config.data.datasets.forEach(function(dataset) {
//				dataset.data.pop();
//			});
//
//			window.myLine.update();
//		});
</script>

