
<div id="sidebar"> <a href="#" class="visible-phone"><i class="icon icon-list"></i> Menu</a>
    <ul>


        <li class=""><a href=""><i class="icon icon-home"></i> <span>Dashboard</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/clientes"><i class="icon icon-group"></i> <span>Clientes</span></a></li>

        <li class="active"><a href="<?= base_url('') ?>/produtos"><i class="icon icon-barcode"></i> <span>Produtos</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/servicos"><i class="icon icon-wrench"></i> <span>Serviços</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/os"><i class="icon icon-tags"></i> <span>Ordens de Serviço</span></a></li>

        


        <li class=""><a href="#" title="faleconosco.php" onClick="abrirnotificacao(this)"><i class="icon icon-hdd"></i> <span>Fale Conosco</span></a></li>

        <li class="submenu">
            <a href="#"><i class="icon icon-money"></i> <span>Financeiro</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul >
                <li><a href="<?= base_url('')?>/financeiro/lancamentos">Lançamentos</a></li>                
            </ul>
        </li>


        


        <li class="submenu ">
            <a href="#"><i class="icon icon-cog"></i> <span>Configurações</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="index.php/usuarios">Usuários</a></li>
                <li><a href="index.php/mapos/emitente">Emitente</a></li>
                <li><a href="index.php/permissoes">Permissões</a></li>
                <li><a href="index.php/mapos/backup">Backup</a></li>
                <li><a  href="#" title="configuraremail" onClick="abrirnotificacao(this)">Email(imap)</a></li>
                <li><a  href="#" title="configurarpagseguro.php" onClick="abrirnotificacao(this)">PagSeguro</a></li>
            </ul>
        </li>


    </ul>
</div>

<div id="content">
    <div id="content-header">
        <div id="breadcrumb"> <a href="" title="Dashboard" class="tip-bottom"><i class="icon-home"></i> Dashboard</a> <a href="index.php/produtos" class="tip-bottom" title="Produtos">Produtos</a> </a> </div>
    </div>    
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                        <?php echo $this->alerta();?>
                <a href="<?= base_url('') ?>/produtos/adicionar" class="btn btn-success"><i class="icon-plus icon-white"></i> Adicionar Produto</a>

                <div class="widget-box">
                    <div class="widget-title">
                        <span class="icon">
                            <i class="icon-barcode"></i>
                        </span>
                        <h5>Produtos</h5>
                    </div>
                    <div class="widget-content nopadding">
                        <table class="table table-bordered ">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Nome</th>
                                    <th>Estoque</th>
                                    <th>Preço</th>
                                    <th>Preço de Venda</th>
                                    <th></th>
                                </tr>
                            </thead><?php
                            $total = 0;
                            foreach ($this->view->produtos as $linha) {
                                $id = count($linha['idProduto']);
                                $total = $total + $id;
                            }
                            if ($total > 0) {
                                ?>
                                <tbody>
                                    <?php foreach ($this->view->produtos as $linha) { ?>
                                        <tr>
                                            <td><?php echo $linha['idProduto'] ?></td>
                                            <td><?php echo $linha['nome_produto'] ?></td>
                                            <td><?php echo $linha['estoque'] ?></td>
                                            <td><?php echo $linha['precoCompra'] ?></td>
                                            <td><?php echo $linha['precoVenda'] ?></td>
                                        
                                            <td colspan="5">
                                                <a href="<?= base_url('') ?>/produtos/visualizar?id=<?= $linha['idProduto'] ?>" style="margin-right: 1%" class="btn tip-top" title="Ver mais detalhes"><i class="icon-eye-open"></i></a>
                                                <a href="<?= base_url('') ?>/produtos/editar?id=<?= $linha['idProduto'] ?>" style="margin-right: 1%" class="btn btn-info tip-top" title="Editar Cliente"><i class="icon-pencil icon-white"></i></a>
                                                <a style="margin-right: 1%" class="btn btn-danger tip-top" title="Excluir Cliente" data-toggle="modal" data-target="#exampleModal" data-whatever="<?=$linha['idProduto'] ?>"><i class="icon-remove icon-white"></i></a>
                                            </td>
                                        </tr>
                                        <tr>                                     
                                
                                <!-- Modal  Excluir Cliente--> 
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title">Excluir Produto</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <form action="<?= base_url('') ?>/produtos/remover" method="POST">
                                                    <h3 style="text-align: center">Deseja realmente excluir este Produto ?</h3>
                                                    <div class="form-group">            
                                                        <input type="hidden" class="form-control" id="recipient-name" name="id" value="">
                                                    </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                                <button type="submit" class="btn btn-danger">Excluir</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                    <?php
                                }
                                ?>                                           

                                </tr>
                                </tbody>
                                <?php
                            } else {
                                ?>
                                <tbody>
                                    <tr>
                                        <td colspan = "5">Nenhum Cliente Cadastrado</td>
                                    </tr>
                                </tbody>
                                <?php
                            }
                            ?>
                        </table>
                    </div>
                </div>








                <script type="text/javascript">
                    //script para passar o id para modal de excluir
                        $('#exampleModal').on('show.bs.modal', function (event) {
                            var button = $(event.relatedTarget) // Button that triggered the modal
                            var recipient = button.data('whatever') // Extract info from data-* attributes
                            // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
                            // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
                            var modal = $(this)

                            modal.find('.modal-body input').val(recipient)
                        });
                    
                    $(document).ready(function () {


                        $(document).on('click', 'a', function (event) {

                            var produto = $(this).attr('produto');
                            $('#idProduto').val(produto);

                        });

                    });

                </script>

            </div>
        </div>
    </div>
</div>
