<div id="sidebar"> <a href="#" class="visible-phone"><i class="icon icon-list"></i> Menu</a>
  <ul>


    <li class=""><a href=""><i class="icon icon-home"></i> <span>Dashboard</span></a></li>
    
            <li class=""><a href="<?= base_url('')?>/clientes"><i class="icon icon-group"></i> <span>Clientes</span></a></li>
        
            <li class="active"><a href="<?= base_url('')?>/produtos"><i class="icon icon-barcode"></i> <span>Produtos</span></a></li>
        
            <li class=""><a href="<?= base_url('')?>/servicos"><i class="icon icon-wrench"></i> <span>Serviços</span></a></li>
    
            <li class=""><a href="<?= base_url('')?>/os"><i class="icon icon-tags"></i> <span>Ordens de Serviço</span></a></li>
    
            
    

<li class=""><a href="#" title="faleconosco.php" onClick="abrirnotificacao(this)"><i class="icon icon-hdd"></i> <span>Fale Conosco</span></a></li>

            <li class="submenu">
          <a href="#"><i class="icon icon-money"></i> <span>Financeiro</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
          <ul >
            <li><a href="<?= base_url('')?>/financeiro/lancamentos">Lançamentos</a></li>            
          </ul>
        </li>
    
           
        <li class="submenu" >
          <a href="#"><i class="icon icon-list-alt"></i> <span>Relatórios</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
          <ul>

                            <li><a href="index.php/relatorios/clientes">Clientes</a></li>
                                        <li><a href="/./LayoutFabrica/relatorios/produtos.php">Produtos</a></li>
                                        <li><a href="/./LayoutFabrica/relatorios/servicos.php">Serviços</a></li>
                                         <li><a href="/./LayoutFabrica/relatorios/os.php">Ordens de Serviço</a></li>
                                        <li><a href="/./LayoutFabrica/relatorios/vendas.php">Vendas(Clientes)</a></li>
                         <li><a title="consultarVendas.php?cache=1" onClick="abrirnotificacao(this)" style="cursor:pointer">vendas(itens)</a></li> 
                            <li><a href="index.php/relatorios/financeiro">Financeiro</a></li>
                        
          </ul>
        </li>

    
            <li class="submenu ">
          <a href="#"><i class="icon icon-cog"></i> <span>Configurações</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
          <ul>
                            <li><a href="index.php/usuarios">Usuários</a></li>
                                        <li><a href="index.php/mapos/emitente">Emitente</a></li>
                                        <!--<li><a href="index.php/permissoes">Permissões</a></li>-->
                                        <!--<li><a href="index.php/mapos/backup">Backup</a></li>-->
            <!-- <li><a  href="#" title="configuraremail" onClick="abrirnotificacao(this)">Email(imap)</a></li>-->
 <li><a  href="#" title="configurarpagseguro.php" onClick="abrirnotificacao(this)">PagSeguro</a></li>
          </ul>
        </li>
        
    
  </ul>
</div>

<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="https://www.ultramapos.online/" title="Dashboard" class="tip-bottom"><i class="icon-home"></i> Dashboard</a> <a href="https://www.ultramapos.online/index.php/produtos" class="tip-bottom" title="Produtos">Produtos</a> <a href="https://www.ultramapos.online/index.php/produtos/visualizar/1139" class="current tip-bottom" title="Visualizar">Visualizar</a> </div>
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
          
                                                
                      <div class="accordion" id="collapse-group">
    <div class="accordion-group widget-box">
        <div class="accordion-heading">
            <div class="widget-title">
                <a data-parent="#collapse-group" href="#collapseGOne" data-toggle="collapse">
                    <span class="icon"><i class="icon-list"></i></span><h5>Dados do Produto</h5>
                </a>
            </div>
        </div>
        
        <div class="collapse in accordion-body">
            <div class="widget-content">
                <table class="table table-bordered">
                    <tbody>
                        <?php foreach ($this->view->produtos1 as $produto){ ?>
                        <tr>
                            <td style="text-align: right; width: 30%"><strong>Descrição</strong></td>
                            <td><?= $produto['nome']?></td>
                        </tr>
                        <tr>
                            <td style="text-align: right"><strong>Unidade</strong></td>
                            <td><?= $produto['unidade']?></td>
                        </tr>
                        <tr>
                            <td style="text-align: right"><strong>Preço de Compra</strong></td>
                            <td><?= $produto['precoCompra']?></td>
                        </tr>
                        <tr>
                            <td style="text-align: right"><strong>Preço de Venda</strong></td>
                            <td><?= $produto['precoVenda']?></td>
                        </tr>
                        <tr>
                            <td style="text-align: right"><strong>Estoque</strong></td>
                            <td><?= $produto['estoque']?></td>
                        </tr>
                        <tr>
                            <td style="text-align: right"><strong>Estoque Mínimo</strong></td>
                            <td><?= $produto['estoqueMinimo']?></td>
                        </tr>
                        <tr>
                            <td style="text-align: right"><strong>Validade</strong></td>
                            <td><?= $produto['validade']?></td>
                        </tr>
                        <?php }?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



      </div>
    </div>
  </div>
</div>
