
<div id="sidebar"> <a href="#" class="visible-phone"><i class="icon icon-list"></i> Menu</a>
    <ul>


        <li class="active"><a href=""><i class="icon icon-home"></i> <span>Dashboard</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/clientes"><i class="icon icon-group"></i> <span>Clientes</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/produtos"><i class="icon icon-barcode"></i> <span>Produtos</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/servicos"><i class="icon icon-wrench"></i> <span>Serviços</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/os"><i class="icon icon-tags"></i> <span>Ordens de Serviço</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/certificados"><i class="icon icon-tags"></i> <span>certificado</span></a></li>


        <li class="submenu ">
            <a href="#"><i class="icon icon-money"></i> <span>Financeiro</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="<?= base_url('') ?>/financeiro/lancamentos">Lançamentos</a></li>             
            </ul>
        </li>
    </ul>
</div>
<div id="content">

    <div id="content-header">        
        <?= $this->AlertaHome(); ?>        
        <div id="breadcrumb"> <a href="<?= base_url('') ?>/dashboard" title="Certificado" class="tip-bottom"><i class="icon-home"></i> Certificado</a> </div>
    </div>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <!--Action boxes-->
                <div class="container-fluid">


<span class="admin-panel__breadcrumb">Admin > Certificado > Cadastro</span>
<section class="admin-content">
   <form class="form" method="POST" action="/certificado/cadastrar">
      <div class="row">
         <div class="col-1-of-2">
            <div class="form__group">
               <label class="form__label">Nome:</label>
               <input class="form__control" type="text" name="nome">
            </div>    
            <div class="form__group">
               <label class="form__label">CPF:</label>
               <input class="form__control" type="text" name="cpf" data-input="CPF">
            </div>    
            <div class="form__group">
               <label class="form__label">RG:</label>
               <input class="form__control" type="text" name="rg">
            </div>    
            <div class="form__group">
               <label class="form__label">Telefone:</label>
               <input class="form__control" type="text" name="telefone" data-input="telefone">
            </div>    
            <div class="form__group">
               <label class="form__label">Email:</label>
               <input class="form__control" type="email" name="email">
            </div>
         </div>

         <div class="col-1-of-2">

            <div class="row no-gap">
               <div class="col-1-of-2">
                  <div class="form__group">
                     <label class="form__label" for="data-inicio">Data Início Curso</label>
                     <input id="data-inicio" class="form__control" type="date" name="dataInicio">
                  </div>
               </div>
               <div class="col-1-of-2">
                  <div class="form__group">
                     <label class="form__label" for="data-fim">Data Fim Curso</label>
                     <input id="data-fim" class="form__control" type="date" name="dataFim">
                  </div>
               </div>
            </div>

            <div class="row no-gap">
               <div class="col-2-of-3">
                  <div class="form__group">
                     <label class="form__label" for="responsavel">Professor(a)</label>
                     <input id="responsavel" class="form__control" type="text" name="responsavel">
                  </div>
               </div>
               <div class="col-1-of-3">
                  <div class="form__group">
                     <label class="form__label" for="carga-horaria">Carga (H)</label>
                     <input id="carga-horaria" class="form__control" type="text" name="cargaHoraria">
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div class="row">
         <div class="col-1-of-2">
            <div class="form__group">
               <label class="form__label">CEP:</label>
               <input class="form__control" type="text" name="cep" data-input="CEP">
            </div>    
            <div class="form__group">
               <label class="form__label">Endereço:</label>
               <input class="form__control" type="text" name="endereco">
            </div>    
            <div class="form__group">
               <label class="form__label">Complemento:</label>
               <input class="form__control" type="text" name="complemento">
            </div>    
            <div class="form__group">
               <label class="form__label">Numero:</label>
               <input class="form__control" type="number" name="numero">
            </div>
         </div>
         <div class="col-1-of-2">
            <div class="form__group">
               <label class="form__label">Bairro:</label>
               <input class="form__control" type="text" name="bairro">
            </div>    
            <div class="form__group">
               <label class="form__label">Cidade:</label>
               <input class="form__control" type="text" name="cidade">
            </div>    
            <div class="form__group">
               <label class="form__label">UF:</label>
               <input class="form__control" type="text" name="uf">
            </div>    
            <div class="form__group">
               <label class="form__label">Logradouro</label>
               <input class="form__control" type="text" name="logradouro">
            </div>    
         </div>
      </div>
      <button class="btn btn--blue pull-right" type="submit">Registrar Certificado <i class="fa fa-arrow-right"></i></button>
   </form>
</section>


</div>
            </div>
        </div>
    </div>
</div>