
<div id="sidebar"> <a href="#" class="visible-phone"><i class="icon icon-list"></i> Menu</a>
    <ul>


        <li class="active"><a href=""><i class="icon icon-home"></i> <span>Dashboard</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/clientes"><i class="icon icon-group"></i> <span>Clientes</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/produtos"><i class="icon icon-barcode"></i> <span>Produtos</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/servicos"><i class="icon icon-wrench"></i> <span>Serviços</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/os"><i class="icon icon-tags"></i> <span>Ordens de Serviço</span></a></li>
        
        <li class=""><a href="<?= base_url('') ?>/certificados"><i class="icon icon-tags"></i> <span>certificado</span></a></li>


        <li class="submenu ">
            <a href="#"><i class="icon icon-money"></i> <span>Financeiro</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="<?= base_url('') ?>/financeiro/lancamentos">Lançamentos</a></li>             
            </ul>
        </li>
    </ul>
</div>
<div id="content">

    <div id="content-header">        
        <?= $this->AlertaHome(); ?>        
        <div id="breadcrumb"> <a href="<?= base_url('') ?>/dashboard" title="Certificado" class="tip-bottom"><i class="icon-home"></i> Certificado</a> </div>
    </div>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <!--Action boxes-->
                <div class="container-fluid">



<section class="admin-content">
   <table class="table">
      <thead>
         <tr>
            <th>Aluno</th>
            <th>Responsavel</th>
            <th>Carga Horária</th>
            <th>Data Início</th>
            <th>Data Fim</th>
         </tr>
      </thead>
      <tbody>
		<?php 
                
                          
			if ($this->view->certificados) :
				foreach ($this->view->certificados as $certificado): 
					$id = $certificado['idCertificado'];
                                        
		?>
			<tr>
				<td><?=$certificado['nome']?></td>
				<td><?=$certificado['responsavel']?></td>
				<td><?=$certificado['cargaHoraria']?> Hora(s)</td>
				<td><?=date("d/m/Y", strtotime($certificado['dataInicio']))?></td>
				<td><?=date("d/m/Y", strtotime($certificado['dataFim']))?></td>
				<td class="table__toggler">
					<i class="fa fa-ellipsis-h"></i>
					<ul class="table__options-group">
                  <li class="table__option"><a href="/admin/certificado/gerar/<?=$id?>"><i class="fa fa-eye"></i> Ver PDF</a></li>
						<li class="table__option"><a href="/admin/certificado/editar/<?=$id?>"><i class="fa fa-pencil"></i> &nbsp;&nbsp;Editar</a></li>
						<li class="table__option"><a href="/admin/certificado/excluir/<?=$id?>"><i class="fa fa-close"></i> &nbsp;Excluir</a></li>
					</ul>
				</td>
			</tr>
		<?php 
				endforeach; 
			endif;
		?>
		</tbody>
   </table>
    
   <a href="/admin/certificado/cadastro" class="admin-content__plus-button u-margin-top-med">
      <i class="fa fa-plus"></i>
   </a>
    
</section>

</div>
            </div>
        </div>
    </div>
</div>
