<!DOCTYPE html>
<html lang="pt-br">
  <head>
   <?php

            //chama as classes
            include_once '../model/Banco.class.php';
            include_once '../model/Funcionario.class.php';
        
            $funcionario = new Funcionario;
            $idFuncionario= $_GET['idFuncionario'];
            $resultado = $funcionario->PesquisarFuncionario($idFuncionario);
    ?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Funcionario</title>
    <link href="../css/bootstrap.min.css" rel="stylesheet">
    <link href="../css/estilo.css" rel="stylesheet">
    <link rel="stylesheet" href="../css/redmond/jquery-ui-1.10.1.custom.css" />
  </head>
  <body>
    <!-- menu inicial -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
            	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-navegacao11">
                	<span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            	<a class="navbar-brand" href="#page-top">Alterar de Funcionário</a>
            </div>
        </div>
    </nav>
    <!-- //menu inicial -->      
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-12">
            <h2 class="bgPadding bg-primary algunsH2">Alterar Funcionário</h2>
        </div>
        <form action="../controller/alterarFuncionario.php" method="post">
                    
                    <div class="form-group">
                        <label class="sr-only">Id</label>
                        <input type="hidden" id="idFuncionario" class="form-control" value="<?php echo $resultado->idFuncionario?>" required autofocus name="idFuncionario">
                    </div>
                    <div class="form-group">
                        <label class="sr-only">Nome</label>
                        <input type="text" id="inputPreco" class="form-control" value="<?php echo $resultado->nome?>" required autofocus name="nome">
                    </div>
                     <div class="form-group">
                        <label for="inputPreco" class="sr-only">CPF</label>
                        <input type="text" id="inputPreco" class="form-control" value="<?php echo $resultado->cpf?>" required autofocus name="cpf">
                    </div>
                    <div class="form-group">
                        <label for="inputPreco" class="sr-only">Perfil</label>
                        <input type="text" id="inputPreco" class="form-control" value="<?php echo $resultado->perfil?>" required autofocus name="perfil">
                    </div>
                    <div class="form-group">
                        <label for="inputPreco" class="sr-only">Login</label>
                        <input type="text" id="inputPreco" class="form-control" value="<?php echo $resultado->login?>" required autofocus name="login">
                    </div>
                    <input type="hidden" value="<?php echo $resultado->senha ;?>" name="senha">
                    <div class="form-group">
                        <label class="sr-only">Cidade</label>
                        <input type="text" id="inputPreco" class="form-control" value="<?php echo $resultado->cidade?>" required autofocus name="cidade">
                    </div>
                     <div class="form-group">
                        <label for="inputPreco" class="sr-only">Cep</label>
                        <input type="text" id="inputPreco" class="form-control" value="<?php echo $resultado->cep?>" required autofocus name="cep">
                    </div>
                    <div class="form-group">
                        <label for="inputPreco" class="sr-only">Endereço</label>
                        <input type="text" id="inputPreco" class="form-control" value="<?php echo $resultado->endereco?>" required autofocus name="endereco">
                    </div>
                    <div class="form-group">
                        <label for="inputPreco" class="sr-only">UF</label>
                        <input type="text" id="inputPreco" class="form-control" value="<?php echo $resultado->uf?>" required autofocus name="uf">
                    </div>
                    <div class="form-group">
                        <label for="inputPreco" class="sr-only">Complemento</label>
                        <input type="text" id="inputPreco" class="form-control" value="<?php echo $resultado->complemento?>" required autofocus name="complemento">
                    </div>
                   
                    <button class="btn btn-lg btn-book-store btn-block" type="submit">Alterar</button>
                </form>
           <br>      
    </div>
</div>     
<footer>Endereço - Mariath Doces</footer>   

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../js/bootstrap.min.js"></script>
    <script src="../js/jquery-1.9.1.js" type="text/javascript"></script>
    <script src="../js/jquery-ui.js" type="text/javascript"></script>
    <script src="../js/calendario.js" type="text/javascript"></script>
    <script>
	$(document).ready(function(){
		$('[data-toggle="tooltip"]').tooltip();   
	});
	</script>
  </body>
</html>


