
    <div class="wrapper">
        <div class="sidebar" data-background-color="white" data-active-color="danger">
            <!--
                Dica 1: você pode alterar a cor do fundo da barra lateral usando: data-background-color = "white | black"
                Dica 2: você pode alterar a cor do botão ativo usando o arquivo data-active-color = "primary | info | success | warning | danger"
            -->
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="#" class="simple-text">
                        Admin
                    </a>
                </div>
                <ul class="nav">
                    <li><a data-toggle="tab" href="#home"><i class="ti-panel"></i><p>Home</p></a></li>
                    <li><a data-toggle="tab" href="#cadastro"><i class="ti-panel"></i><p>Cadastro</p></a></li>
                    <li><a data-toggle="tab" href="#estoque"><i class="ti-panel"></i><p>Estoque</p></a></li>
                    <li><a data-toggle="tab" href="#Conferencia"><i class="ti-panel"></i><p>Conferencia</p></a></li>
                    <li><a data-toggle="tab" href="#relatorio"><i class="ti-panel"></i><p>Relatorios</p></a></li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar bar1"></span>
                            <span class="icon-bar bar2"></span>
                            <span class="icon-bar bar3"></span>
                        </button>
                        <a class="navbar-brand" href="#">Painel de Controle - Produtos</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="ti-bell"></i>
                                    <p class="notification">4</p>
                                    <p>Notificações</p>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Notificação 1</a></li>
                                    <li><a href="#">Notificação 2</a></li>
                                    <li><a href="#">Notificação 3</a></li>
                                    <li><a href="#">Notificação 4</a></li>
                                </ul>
                            </li>
                            <li class="Settings">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="ti-settings"></i>
                                    <p class="notification"></p>
                                    <p>Opções</p>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    Seleção de Cor:
                                    <li>
                                        <input type="radio" value="Preto" ng-model="cor" />
                                        <img src="#" id="image" />
                                    </li>
                                    <li>
                                        <input type="radio" value="Braco" ng-model="cor" />
                                        <img src="#" id="image1" />
                                        {{black}}
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="content">
                <div class="container-fluid">
                    <div class="tab-content">
                        <div id="home" class="tab-pane fade in active">
                            <div class="row">
                                <div class="col-lg-3 col-sm-6">
                                    <div class="card">
                                        <div class="content">
                                            <div class="row">
                                                <div class="col-xs-5">
                                                    <div class="icon-big icon-warning text-center">
                                                        <i class="ti-server"></i>
                                                    </div>
                                                </div>
                                                <div class="col-xs-7">
                                                    <div class="numbers">
                                                        <p>Qtd. Produtos em estoque</p>
                                                        105
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="footer">
                                                <hr />
                                                <div class="stats">
                                                    <i class="ti-reload"></i> Atualizar
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="card">
                                        <div class="content">
                                            <div class="row">
                                                <div class="col-xs-5">
                                                    <div class="icon-big icon-success text-center">
                                                        <i class="ti-wallet"></i>
                                                    </div>
                                                </div>
                                                <div class="col-xs-7">
                                                    <div class="numbers">
                                                        <p>Qtd. Orçamentos</p>
                                                        34
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="footer">
                                                <hr />
                                                <div class="stats">
                                                    <i class="ti-reload"></i> Atualizar
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="card">
                                        <div class="content">
                                            <div class="row">
                                                <div class="col-xs-5">
                                                    <div class="icon-big icon-danger text-center">
                                                        <i class="ti-pulse"></i>
                                                    </div>
                                                </div>
                                                <div class="col-xs-7">
                                                    <div class="numbers">
                                                        <p>texto</p>
                                                        23
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="footer">
                                                <hr />
                                                <div class="stats">
                                                    <i class="ti-reload"></i> Atualizar
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="card">
                                        <div class="content">
                                            <div class="row">
                                                <div class="col-xs-5">
                                                    <div class="icon-big icon-info text-center">
                                                        <i class="ti-pulse"></i>
                                                    </div>
                                                </div>
                                                <div class="col-xs-7">
                                                    <div class="numbers">
                                                        <p>texto</p>
                                                        45
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="footer">
                                                <hr />
                                                <div class="stats">
                                                    <i class="ti-reload"></i> Atualizar
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="cadastro" class="tab-pane fade">
                            <div id="New_Candidato">
                                <div class="row">
                                    <div class="col-lg-4 col-md-5">
                                        <div class="card card-user">
                                            <div class="image">
                                                <img src="/admin/img/background.jpg" alt="..." />
                                            </div>
                                            <div class="content" style="min-height: 0px;">
                                                <div class="author">
                                                    <img class="avatar border-white" src="/admin/img/new_logo.png" alt="..." style="border: 0px solid #FFFFFF;" />

                                                </div><br />
                                                <p class="description text-center">
                                                    <h6><b>Nome do produto:</b> {{}}</h6><br />
                                                    <h6><b>Descrição:</b> </h6><br />

                                                </p>
                                            </div>
                                            <hr>
                                            <div class="text-center">
                                                <div class="row">
                                                    <div class="col-md-3 col-md-offset-1">
                                                        <h5><br /><small></small></h5>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <h5>12<br /><small>Quantidade Total</small></h5>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <h5><br /><small></small></h5>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="card">
                                            <div class="header">
                                                <h4 class="title">Data de Atualizaçãoões:</h4>
                                            </div>
                                            <div class="content">
                                                <ul class="list-unstyled team-members">
                                                    <li ng-repeat="">
                                                        <div class="row">
                                                            <div class="col-xs-3">
                                                                <div class="avatar">
                                                                    <img src="/admin/img/faces/face-0.jpg" alt="Circle Image" class="img-circle img-no-padding img-responsive">
                                                                </div>
                                                            </div>
                                                            <div class="col-xs-6">

                                                                <br />
                                                                <span class="text-muted"><small>teste</small></span>
                                                            </div>
                                                            <div class="col-xs-3 text-right">
                                                                <btn class="btn btn-sm btn-success btn-icon"><i class="fa fa-envelope"></i></btn>
                                                            </div>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- -----------------------------------------  -->
                                    <!--  ----------------------------------------  -->
                                    <!--              Cadastrar Produto             -->
                                    <!--  ----------------------------------------  -->
                                    <!--  ----------------------------------------  -->
                                    <div class="col-lg-8 col-md-7">
                                        <div class="card">
                                            <div class="header">
                                                <h4 class="title">Cadastrar Categoria</h4>
                                            </div>
                                            <div class="content">
                                                <div class="text-center">
                                                    <button type="submit" disabled class="btn btn-info btn-fill btn-wd">Cadastrar Categoria</button>
                                                    <button type="submit" disabled class="btn btn-info btn-fill btn-wd">Consultar Categoria</button>
                                                    <button type="submit" disabled class="btn btn-info btn-fill btn-wd">Cadastrar Produto</button>
                                                    <button type="submit" disabled class="btn btn-info btn-fill btn-wd">Consultar Produto</button>
                                                    <button type="submit" disabled class="btn btn-info btn-fill btn-wd">Cadastrar Cliente</button>
                                                    <button type="submit" disabled class="btn btn-info btn-fill btn-wd">Consultar Cliente</button>
                                                </div>
                                                <br /><br />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-8 col-md-7">
                                        <div class="card">
                                            <div class="header">
                                                <h4 class="title">Consultar Produto</h4>
                                            </div>
                                            <div class="content">
                                                <form>
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <div class="form-group">
                                                                <label>Nome produto</label>
                                                                <input type="text" class="form-control border-input" disabled placeholder="nomep" value="{{}}">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <div class="form-group">
                                                                <label>Status</label>
                                                                <select class="form-control border-input">
                                                                    <option value="status">-</option>
                                                                    <option value="status1">Ativo</option>
                                                                    <option value="status2">Inativo</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="text-center">
                                                        <button type="submit" disabled class="btn btn-danger btn-fill btn-wd btn-block">Cancelar</button>
                                                        <button type="submit" disabled class="btn btn-success btn-fill btn-wd btn-block">Consultar</button>
                                                    </div>
                                                    <div class="text-center">
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-lg-12">
                                        <div class="card">
                                            <div class="header">
                                                <h4 class="title">Cadastrar Produto</h4>
                                            </div>
                                            <div class="content">
                                                <form method="POST" action="/dashboard/cadastro-produto">
                                                    <div class="row">
                                                        <div class="col-md-5">
                                                            <div class="form-group">
                                                                <label>Nome produto</label>
                                                                <input type="text" class="form-control border-input" name="nome" placeholder="nomep" value="{{}}">
                                                            </div>
                                                        </div>
                                                        <div class="col-md-7">
                                                            <div class="form-group">
                                                                <label>Categoria/Cassificação</label>
                                                                <select class="form-control border-input" name="categoria">
                                                                    <option value="categoria">-</option>
                                                                    <option value="categoria1">Categoria1</option>
                                                                    <option value="categoria2">Categoria3</option>
                                                                    <option value="categoria3">Categoria4</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-md-6">
                                                            <div class="form-group">
                                                                <label>Valor De venda</label>
                                                                <input type="text" class="form-control border-input" name="valorUnitario"  placeholder="Valor Unitario" value="{{}}" />
                                                            </div>
                                                        </div>
                                                        <div class="col-md-6">
                                                            <div class="form-group">
                                                                <label>Valor De Compra</label>
                                                                <input type="text" class="form-control border-input" name="valorGasto"  placeholder="Valor Unitario" value="{{}}" />
                                                            </div>
                                                        </div>
                                                        <div class="col-md-6" >
                                                            <div class="form-group">
                                                                <label>Quantidade</label>
                                                                <input type="number" class="form-control border-input"  name="qtd" placeholder="Quantidade" value="{{}}" />
                                                            </div>
                                                        </div>
                                                        <div class="col-md-6">
                                                            <div class="form-group">
                                                                <label>Quantidade Minima</label>
                                                                <input type="number" class="form-control border-input" name="qtdMin" placeholder="Quantidade minima" value="{{}}" />
                                                            </div>
                                                        </div>
                                                        <div class="col-md-3" style="margin-left: 10px;">
                                                            <div class="form-group">
                                                                <label>Validade</label>
                                                                <input type="date" class="form-control border-input" name="validade"  placeholder="Validade do produto" value="{{}}" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                    
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <div class="form-group">
                                                                <label>Descrição</label>
                                                                <textarea rows="5" class="form-control border-input" disabled placeholder="Here can be your description" value="Mike">
                                                                    textotextotextotextotexto,textotextotexto.
                                                                    textotextotexto,textotextotextotexto, textotexto.
                                                                    textotextotextotextotexto,textotextotexto.
                                                                    textotextotexto,textotextotextotexto, textotexto.
                                                                </textarea>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="text-center">
                                                        <button type="submit"  class="btn btn-danger btn-fill btn-wd btn-block">Cancelar</button>
                                                        <button type="submit"  class="btn btn-success btn-fill btn-wd btn-block">Cadastrar</button>
                                                    </div>
                                                    <div class="text-center">
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </form>
                                            </div>
                                        </div>
                                 
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="estoque" class="tab-pane fade">
                            estoque
                        </div>
                        <div id="Conferencia" class="tab-pane fade">
                            Conferencia
                        </div>
                        <div id="relatorio" class="tab-pane fade">
                            relatorio
                        </div>
                    </div>
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="#">
                                    Creative Tim
                                </a>
                            </li>

                            <li>
                                <a href="#">
                                    Projeção
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div class="copyright pull-right">
                        &copy;
                        <script>document.write(new Date().getFullYear())</script>, desenvolvido por Fabrica de Software <i class="fa fa-heart heart"></i> by <a href="#">Projeção</a>
                    </div>
                </div>
            </footer>
        </div>
    </div>



