<?php
session_start();
?>
<!DOCTYPE html>
<html lang="pt-br">
    <head>        
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Funcionário</title>
        <link href="/public/css/bootstrap.min.css" rel="stylesheet">
        <link href="/public/css/estilo.css" rel="stylesheet">
        <link rel="stylesheet" href="/public/css/redmond/jquery-ui-1.10.1.custom.css" />
    </head>
    <body>
        <!-- menu inicial -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-navegacao11">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#page-top">Cadastro de Cliente</a>
                </div>
            </div>
        </nav>
        <!-- //menu inicial -->      
        <div class="container">
            
            <div class="row">
                <div class="col-xs-12 col-md-12">
                    <h2 class="bgPadding bg-primary algunsH2">Editar Clientes</h2>
                </div>
                <?php
                $this->alerta();
//                $sessoes = $_SESSION['danger']['nome'] ;
//                foreach ($_SESSION['danger'] as $sessao ){
//                    echo $sessao ;
//                }
//                ?>

                <?php 
               
                
                $dados = $this->view->clientesEditar;
                         $id = $dados[0]->idCliente;
                         $nome = $dados[0]->nome;
                         $cpf = $dados[0]->cpf;
                         $email = $dados[0]->email;
                         $login = $dados[0]->login;
                         $cidade = $dados[0]->cidade;
                         $cep = $dados[0]->cep;
                         $endereco = $dados[0]->endereco;
                         $uf = $dados[0]->uf;
                         $complemento= $dados[0]->complemento;
                ?>
                <form  action = "/dashboard/update/cliente"  method="POST" enctype = "multipart/form-data">
                    <div class = "col-xs-12">
                        <div class = "form-group <?php if(is_null($this->alerta())){echo '';}else{echo 'has-error'; }?>">
                            <input TYPE="hidden" name="id" value="<?=$id?>">
                            <label for = "Nome">Nome</label>
                            <input type = "text" class = "form-control" name = "nome" value="<?=$nome?>" placeholder = "Rodrigo" />
                        </div>
                        <div class = "form-group">                            
                            <label for = "cep">CPF</label>
                            <input type = "text" class = "form-control" name = "cpf"  value="<?=$cpf?>" />
                        </div>
                        <div class = "form-group"> 
                            <label for = "tipo">Tipo Cliente</label>
                            <select class = "form-control" id = "tipoCliente" name = "tipoCliente">
                                <option>-</option>
                                <option value = "P.F.">Pessoa Fisiaca</option>
                                <option value = "P.J.">Pessoa Juridica</option>

                            </select>
                        </div>
                        <div class = "form-group"> 
                            <label for = "email">E-mail</label>
                            <input type = "text" class = "form-control" name = "email" value="<?=$email?>" />
                        </div>
                        <div class = "form-group"> 
                            <label for = "login">Login</label>
                            <input type = "text" class = "form-control" name = "login" value="<?=$login?>" />
                        </div>
                        <div class = "form-group"> 
                            <label for = "senha">Senha</label>
                            <input type = "password" class = "form-control" name = "senha"  />
                        </div>
                        <div class = "form-group"> 
                            <label for = "senha">Confirma Senha</label>
                            <input type = "password" class = "form-control" name = "confirmaSenha"  />

                        </div>
                    </div>
                    <div class = "container">
                        <div class = "row">
                            <div class = "col-xs-12 col-md-12">
                                <h2 class = "bgPadding bg-primary algunsH2">Endereço</h2>
                            </div>

                            <div class = "col-xs-12">
                                <div class = "form-group">
                                    <label for = "cidade">Cidade</label>
                                    <input type = "text" class = "form-control" name = "cidade" placeholder = "Brasília" value="<?=$cidade?>" />
                                </div>
                                <div class = "form-group"> 
                                    <label for = "cep">CEP</label>
                                    <input type = "text" class = "form-control" name = "cep" value="<?=$cep?>" />
                                </div>
                                <div class = "form-group"> 
                                    <label for = "endereco">Endereco</label>
                                    <input type = "text" class = "form-control" name = "endereco" value="<?=$endereco?>" />
                                </div>
                                <div class = "form-group"> 
                                    <label for = "uf">UF</label>
                                    <input type = "text" class = "form-control" name = "uf" value="<?=$uf?>" />
                                </div>
                                <div class = "form-group"> 
                                    <label for = "complemento">Complemento</label>
                                    <input type = "text" class = "form-control" name = "complemento" value="<?=$complemento?>" />
                                </div>
                            </div>

                            <br>
                        </div>
                    </div>
                    <div class = "col-xs-12">
                        <div class = "form-group"><br>
                            <input type = "submit" value = "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Editar &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" class = "btn btn-primary btn-lg" />
                            <a href="/dashboard/listar/clientes"  class="btn btn-info" >Voltar</a></td>
                        </div>
                    </div>
                </form>
                <br>
            </div>
        </div> Funcionário - Mariath Doces</footer>

    <!--jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/public/js/bootstrap.min.js"></script>
    <script src="/public/js/jquery-1.9.1.js" type="text/javascript"></script>
    <script src="/public/js/jquery-ui.js" type="text/javascript"></script>
    <script src="/public/js/calendario.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $('[data-toggle = "tooltip"]').tooltip();
        });
    </script>
</body>
</html>