<!DOCTYPE html>
<html lang="pt-br">
  <head>
       <?php

            //chama as classes
            include_once '../model/Banco.class.php';
            include_once '../model/Funcionario.class.php';

            $funcionario = new Funcionario;
            $lista  = $funcionario->Listar();
        ?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Funcionário</title>
    <link href="../css/bootstrap.min.css" rel="stylesheet">
    <link href="../css/estilo.css" rel="stylesheet">
    <link rel="stylesheet" href="../css/redmond/jquery-ui-1.10.1.custom.css">
  </head>
  <body>
    <!-- menu inicial -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
            	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-navegacao11">
                	<span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            	<a class="navbar-brand" href="#page-top">Funcionário</a>
            </div>
        </div>
    </nav>
    <!-- //menu inicial -->   
<div class="container">
    <div class="row">
    	<div class="col-xs-12">
            <a href="cadastrar-funcionario.php">
            <button type="button" class="btn btn-default"   pull-left> &nbsp;&nbsp;+&nbsp; Novo &nbsp;&nbsp;&nbsp;</button>
            </a>
        </div>
      
        <div class="col-xs-12">
            <h2 class="bgPadding bg-primary">Lista de Endereço</h2>
        </div>
		<div class="col-xs-12">
            <table class="table table-striped">                
            	<thead>
                    <tr>
                        <th>ID</th>
                        <th>Nome</th>
                        <th>CPF</th>
                        <th>Perfil</th>
                        <th>Login</th>
                        <th>Cidade</th>
                        <th>CEP</th>
                        <th>Endereço</th>
                        <th>UF</th>
                        <th>Complemento</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>                                  
                <tbody>
                    
 <tbody>
                      <?php foreach($lista as $linha):?>
                    <tr>
                      <td><?php echo $linha['idFuncionario']?></td>
                      <td><?php echo $linha['nome']?></td>
                      <td><?php echo $linha['cpf']?></td>
                      <td><?php echo $linha['perfil']?></td>
                      <td><?php echo $linha['login']?></td>
                      <td><?php echo $linha['cidade']?></td>
                      <td><?php echo $linha['cep']?></td>
                      <td><?php echo $linha['endereco']?></td>
                      <td><?php echo $linha['uf']?></td>
                      <td><?php echo $linha['complemento']?></td>
                      <td><a href="alterar-funcionario.php?idFuncionario=<?php echo $linha['idFuncionario']?>" class="btn btn-info">Atualizar</a></td>
                      <td><a href="../controller/excluirFuncionario.php?idFuncionario=<?php echo $linha['idFuncionario']?>" class="btn btn-danger">Excluir</a></td>
                      
                    </tr>
                      <?php endforeach?>
                  </tbody><!-- janela modal Editar Funcionário -->     

                  	          
                </tbody>
            </table>
        </div>
    </div>
</div>     
<footer>Sistema Teste &copy; 2018 &nbsp;|&nbsp; Prof. Ricardo Lima Amaral </footer>   

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../js/bootstrap.min.js"></script>
    <script src="../js/jquery-1.9.1.js" type="text/javascript"></script>
    <script src="../js/jquery-ui.js" type="text/javascript"></script>
    <script src="../js/calendario.js" type="text/javascript"></script>
  </body>
</html>

