<!DOCTYPE html>
<html lang="pt-br">
    <head>       
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Cliente</title>
        <link href="/public/css/bootstrap.min.css" rel="stylesheet">
        <link href="/public/css/estilo.css" rel="stylesheet">
        <link rel="stylesheet" href="/public/css/redmond/jquery-ui-1.10.1.custom.css">
    </head>
    <body>
        <!-- menu inicial -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-navegacao11">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#page-top">Cliente</a>
                </div>
            </div>
        </nav>
        <!-- //menu inicial -->   
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <a href="cadastrar-cliente.php">
                        <button type="button" class="btn btn-default"   pull-left> &nbsp;&nbsp;+&nbsp; Novo &nbsp;&nbsp;&nbsp;</button>
                    </a>
                </div>

                <div class="col-xs-12">
                    <h2 class="bgPadding bg-primary">Lista de Endereço</h2>
                </div>

                <div class="col-xs-12">
                    <table class="table table-striped">                
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nome</th>
                                <th>CPF</th>
                                <th>Tipo Cliente</th>
                                <th>E-mail</th>
                                <th>Login</th>
                                <th>Cidade</th>
                                <th>CEP</th>
                                <th>Endereço</th>
                                <th>UF</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>                                  
                        <tbody>

                        <tbody>
                            <?php foreach ($this->view->clientes as $linha): ?>
                                <tr>
                                    <td><?php echo $linha->idCliente ?></td>
                                    <td><?php echo $linha->nome ?></td>
                                    <td><?php echo $linha->cpf ?></td>
                                    <td><?php echo $linha->tipoCliente ?></td>
                                    <td><?php echo $linha->email ?></td>
                                    <td><?php echo $linha->login ?></td>
                                    <td><?php echo $linha->cidade ?></td>
                                    <td><?php echo $linha->cep ?></td>
                                    <td><?php echo $linha->endereco ?></td>
                                    <td><?php echo $linha->uf ?></td>
                                    <td><a href="/dashboard/alterar/cliente/<?php echo $linha->idCliente ?>"  class="btn btn-info" >Atualizar</a></td>
                                    <td><a  class="btn btn-danger">Excluir</a></td>
                                </tr>
                            <?php endforeach ?>
                        </tbody><!-- janela modal Editar Cliente -->   

                        <!-- Modal -->
                        <div class="modal fade" id="atualizarModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                                    </div>
                                    <div class="modal-body">                                        
                                        <form action="" method="POST">
                                            <div class="form-group">
                                                <label for="Nome">Nome: </label>
                                                <input type="" class="form-control" name="" value="">
                                                <label for="CPF">CPF: </label>
                                                <input type="" class="form-control" name="">
                                            </div>
                                            <div class="form-group">
                                                <label for="Tipo">Tipo Cliente:</label>
                                                <select class="form-control" id="tipoCliente" name="tipoCliente">
                                                    <option>-</option>
                                                    <option value="P.F.">Pessoa Fisica</option>
                                                    <option value="P.J.">Pessoa Juridica</option>

                                                </select>
                                                <label for="E-mail">E-mail:</label>
                                                <input type="email" class="form-control" name="email">
                                            </div>
                                            <div class="form-group">
                                                <label for="Login">Login: </label>
                                                <input type="text" class="form-control" name="login">
                                                <label for="cidade">Cidade:</label>
                                                <input type="text" class="form-control" name="cidade">
                                            </div>
                                            <div class="form-group">
                                                <label for="cep">CEP:</label>
                                                <input type="text" class="form-control" name="cep">
                                                <label for="endereco">Endereço: </label>
                                                <input type="text" class="form-control" name="endereco">
                                            </div>
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        <button type="button" class="btn btn-primary">Save changes</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>     
        <footer>Sistema Teste &copy; 2018 &nbsp;|&nbsp; Prof. Ricardo Lima Amaral </footer>   
        <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="../js/bootstrap.min.js"></script>
        <script src="../js/jquery-1.9.1.js" type="text/javascript"></script>
        <script src="../js/jquery-ui.js" type="text/javascript"></script>
        <script src="../js/calendario.js" type="text/javascript"></script>
    </body>
</html>

