<div id="sidebar"> <a href="#" class="visible-phone"><i class="icon icon-list"></i> Menu</a>
    <ul>


        <li class=""><a href=""><i class="icon icon-home"></i> <span>Dashboard</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/clientes"><i class="icon icon-group"></i> <span>Clientes</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/produtos"><i class="icon icon-barcode"></i> <span>Produtos</span></a></li>

        <li class="active"><a href="<?= base_url('') ?>/servicos"><i class="icon icon-wrench"></i> <span>Serviços</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/os"><i class="icon icon-tags"></i> <span>Ordens de Serviço</span></a></li>


        <li class="submenu ">
            <a href="#"><i class="icon icon-money"></i> <span>Financeiro</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="<?= base_url('') ?>/financeiro/lancamentos">Lançamentos</a></li>

            </ul>
        </li>
    </ul>
</div>


<div id="content">
    <div id="content-header">
        <?= $this->AlertaHome(); ?> 
        <div id="breadcrumb"> <a href="<?= base_url('') ?>/dashboard" title="Dashboard" class="tip-bottom"><i class="icon-home"></i> Dashboard</a> <a href="https://www.ultramapos.online/index.php/servicos" class="tip-bottom" title="Servicos">Servicos</a> <a href="https://www.ultramapos.online/index.php/servicos/editar/81" class="current tip-bottom" title="Editar">Editar</a> </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">


                <div class="row-fluid" style="margin-top:0">
                    <div class="span12">
                        <div class="widget-box">
                            <div class="widget-title">
                                <span class="icon">
                                    <i class="icon-align-justify"></i>
                                </span>
                                <h5>Editar Serviço</h5>
                            </div>
                            <div class="widget-content nopadding">
                                <form action="<?= base_url('') ?>/servicos/adicionar/update" id="formServico" method="post" class="form-horizontal" >
                                    <?php foreach ($this->view->oneServico as $servico) { ?>
                                        <input type="hidden" name="idServicos" value="<?= $servico['idServicos'] ?>" />
                                        <div class="control-group">
                                            <label for="nome" class="control-label">Nome<span class="required">*</span></label>
                                            <div class="controls">
                                                <input id="nome" type="text" name="nome" value="<?= $servico['nome_servico'] ?>"  />
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label for="preco" class="control-label"><span class="required">Preço*</span></label>
                                            <div class="controls">
                                                <input id="preco" class="money" type="text" name="preco" value="<?= $servico['preco'] ?>"  />
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label for="descricao" class="control-label">Descrição</label>
                                            <div class="controls">
                                                <input id="descricao" type="text" name="descricao" value="<?= $servico['descricao'] ?>"  />
                                            </div>
                                        </div>
                                    <?php } ?>
                                    <div class="form-actions">
                                        <div class="span12">
                                            <div class="span6 offset3">
                                                <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Alterar</button>
                                                <a href="<?= base_url('') ?>/servicos" id="btnAdicionar" class="btn"><i class="icon-arrow-left"></i> Voltar</a>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <script type="text/javascript">
                    $(document).ready(function () {
                        $(".money").maskMoney();
                        $('#formServico').validate({
                            rules: {
                                nome: {required: true},
                                preco: {required: true}
                            },
                            messages: {
                                nome: {required: 'Campo Requerido.'},
                                preco: {required: 'Campo Requerido.'}
                            },

                            errorClass: "help-inline",
                            errorElement: "span",
                            highlight: function (element, errorClass, validClass) {
                                $(element).parents('.control-group').addClass('error');
                            },
                            unhighlight: function (element, errorClass, validClass) {
                                $(element).parents('.control-group').removeClass('error');
                                $(element).parents('.control-group').addClass('success');
                            }
                        });
                    });
                </script>
            </div>
        </div>
    </div>
</div>
