<!DOCTYPE html>
<html lang="pt-BR" >

<head>
  <meta charset="UTF-8">
  <title>ERRO - Rota</title>
  <link>
  <link rel="stylesheet" href="<?= base_url('')?>/public/home/css/404.css">
</head>
  <body>
  <section id="not-found">
    <div id="title">Rota Não encontrada</div>
    <div id="title">Verifique as configurações de rotas em routes.php</div>
    <div class="circles">
      <p>404<br>
       <small>Error</small>       
      </p>
      <span class="circle big"></span>
      <span class="circle med"></span>
      <span class="circle small"></span>
    </div>
  </section>
 </body>
  <script src='<?= base_url('')?>/public/home/js/jquery.js'></script>
    <script  src="<?= base_url('')?>/public/home/js/404.js"></script>
</body>
</html>

