
<div id="sidebar"> <a href="#" class="visible-phone"><i class="icon icon-list"></i> Menu</a>
  <ul>


    <li class=""><a href=""><i class="icon icon-home"></i> <span>Dashboard</span></a></li>
    
            <li class=""><a href="<?= base_url('')?>/clientes"><i class="icon icon-group"></i> <span>Clientes</span></a></li>
        
            <li class=""><a href="<?= base_url('')?>/produtos"><i class="icon icon-barcode"></i> <span>Produtos</span></a></li>
        
            <li class=""><a href="<?= base_url('')?>/servicos"><i class="icon icon-wrench"></i> <span>Serviços</span></a></li>
    
            <li class="active"><a href="<?= base_url('')?>/os"><i class="icon icon-tags"></i> <span>Ordens de Serviço</span></a></li>
    
            
        
            

            
    
            
        <li class="submenu ">
            <a href="#"><i class="icon icon-money"></i> <span>Financeiro</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="<?= base_url('')?>/financeiro/lancamentos">Lançamentos</a></li>                
            </ul>
        </li>

    
            <li class="submenu ">
          <a href="#"><i class="icon icon-cog"></i> <span>Configurações</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
          <ul>
                            <li><a href="index.php/usuarios">Usuários</a></li>
                                        <li><a href="index.php/mapos/emitente">Emitente</a></li>
                                        <!--<li><a href="index.php/permissoes">Permissões</a></li>-->
                                        <!--<li><a href="index.php/mapos/backup">Backup</a></li>-->
            <!-- <li><a  href="#" title="configuraremail" onClick="abrirnotificacao(this)">Email(imap)</a></li>-->
 <li><a  href="#" title="configurarpagseguro.php" onClick="abrirnotificacao(this)">PagSeguro</a></li>
          </ul>
        </li>
        
    
  </ul>
</div>

<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="<?= base_url('')?>" title="Dashboard" class="tip-bottom"><i class="icon-home"></i> Dashboard</a> <a href="<?= base_url('')?>/os" class="tip-bottom" title="Os">Os</a> <a href="<?= base_url('')?>/os/adicionar" class="current tip-bottom" title="Adicionar">Adicionar</a> </div>
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
          
                                                
                      <style> 
.ui-autocomplete-loading { background:url(http://sintaxse.com/mapos/img/ajax-loader2.gif) no-repeat right center;
width:1px;
height:1px;
margin-right:10px;
};

</style>



<link rel="stylesheet" href="https://www.ultramapos.online/js/jquery-ui/css/smoothness/jquery-ui-1.9.2.custom.css" />
<script type="text/javascript" src="https://www.ultramapos.online/js/jquery-ui/js/jquery-ui-1.9.2.custom.js"></script>
<script type="text/javascript" src="https://www.ultramapos.online/js/jquery.validate.js"></script>
<div class="row-fluid" style="margin-top:0">
    <div class="span12">
        <div class="widget-box">
            <div class="container-fluid col-sm-5  nopadding" style="margin-left: 3%;">
                        <?php
                        $this->alerta();
                        ?>
                    </div>
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-tags"></i>
                </span>
                <h5>Cadastro de OS</h5>
            </div>
            <div class="widget-content nopadding">
                

                <div class="span12" id="divProdutosServicos" style=" margin-left: 0">
                    <ul class="nav nav-tabs">
                        <li class="active" id="tabDetalhes"><a href="#tab1" data-toggle="tab">Detalhes da OS</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="tab1">

                          <div class="span12" id="divCadastrarOs">
                              
                                <div id="diverror" class="span12 alert alert-danger" id="divInfo" style="padding: 1%; display:none" >Dados incompletos, verifique os campos com asterisco ou se selecionou corretamente cliente e responsável.</div>
                            
                                <form action="<?= base_url("")?>/os/adicionar/salvar" method="post" enctype="multipart/form-data" id="formOs" >

                                    <div class="span12" style="padding: 1%">
                                        <div class="span6">
                                                                <label for="cliente">Cliente*</label>

                                                                <select class="span12" name="idClientes">                                                            
                                                                    <?php foreach ($this->view->allClientes as $allCliente) { ?>
                                                                        <option value="<?= $allCliente['idClientes'] ?>">
                                                                            <?php echo $allCliente['nomeCliente']; ?>
                                                                        </option>                                                            
                                                                    <?php } ?>

                                                                </select>
                                                                <input id="clientes_id" class="span12" type="hidden" name="clientes_id" value=""  />
                                                            </div>
                                                            <div class="span6">
                                                                <label for="tecnico">Técnico / Responsável*</label>


                                                                <select class="span12" name="idUsuario">                                                            
                                                                    <?php foreach ($this->view->allUsuario as $allUsuario) { ?>
                                                                        <option value="<?= $allUsuario['idUsuarios']; ?>">
                                                                            <?php echo $allUsuario['nome_usuario']; ?>
                                                                        </option>                                                            
                                                                    <?php } ?>

                                                                </select>
                                                            </div>
                                    </div>
                                    <div class="span12" style="padding: 1%; margin-left: 0">
                                        <div class="span2">
                                            <label for="status">Status<span class="required">*</span></label>
                                            <select class="span12" name="status" id="status" >
                                                <option value="Orçamento">Orçamento</option>
                                               <option value="Aberto">Aberto</option>
                                                <option value="Em Andamento">Em Andamento</option>
                                                <option value="Finalizado">Finalizado</option>
                                                <option value="Cancelado">Cancelado</option>
                                            </select>
                                        </div>
                                        <div class="span2">
                                            <label for="dataInicial">Data Inicial<span class="required">*</span></label>
                                            <input id="dataInicial" class="span12 datepicker" type="date" name="dataInicial" value=""  />
                                        </div>
                                        <div class="span2">
                                            <label for="dataFinal">Data Final</label>
                                            <input id="dataFinal" class="span12 datepicker" type="date" name="dataFinal" value=""  />
                                        </div>
                                        <div class="span2">
                                            <label for="telefone">Telefone</label>
                                            <input id="telefone" class="span12" type="tel" name="telefone" value="">
                                        </div>
                                        <div class="span1">
                                            <label for="quantidade">Quantidade</label>
                                            <input id="quantidade" class="span12" type="number" name="quantidade" value="">
                                        </div>
                                        <div class="span3">
                                            <label for="cidade">Cidade</label>
                                            <input id="cidade" class="span8" type="text" name="cidade" value="">
                                        </div>
                                        
                                        
                                    </div>

                                    <div class="span12" style="padding: 1%; margin-left: 0">
                                        
                                        
                                        
                                        <div class="span12" style="padding: 1%; margin-left: 0">
                                        <div class="span6">
                                            <label for="descricaoServico">Descrição Serviço</label>
                                            <textarea class="span12" name="descricaoServico" id="descricaoServico" cols="30" rows="5"></textarea>
                                        </div>
                                        <div class="span6">
                                            <label for="produtos">Produtos</label>
                                            <textarea class="span12" name="produtos" id="produtos" cols="30" rows="5"></textarea>
                                        </div>
                                        </div>

                                    </div>
                                    
                                    <div class="span12" style="padding: 1%; margin-left: 0">
                                        <div class="span6 offset3" style="text-align: center">
                                            <button class="btn btn-success" id="btnContinuar"><i class="icon-share-alt icon-white"></i> Continuar</button>
                                            <a href="<?= base_url('');?>/os" class="btn"><i class="icon-arrow-left"></i> Voltar</a>
                                        </div>
                                    </div>
                                </form>
                      </div>

                        </div>

                    </div>

                </div>               
.
        </div>
        
    </div>
</div>
</div>



<script type="text/javascript">


//     $("#tecnico").autocomplete({
//            source: "index.php/os/autoCompleteUsuario",
//       minLength: 1,
//            select: function( event, ui ) {

//                 $("#usuarios_id").val(ui.item.id);

//
//            }
//      });

      
      

      $("#formOs").validate({
          rules:{
             cliente: {required:true},
             tecnico: {required:true},
             dataInicial: {required:true}
          },
          messages:{
             cliente: {required: 'Campo Requerido.'},
             tecnico: {required: 'Campo Requerido.'},
             dataInicial: {required: 'Campo Requerido.'}
          },

            errorClass: "help-inline",
            errorElement: "span",
            highlight:function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            }
       });

    $(".datepicker" ).datepicker({ dateFormat: 'dd/mm/yy' });
   
});


	

</script>



      </div>
    </div>
  </div>
</div>
<!--Footer-part-->
<div class="row-fluid">
  <div id="footer" class="span12"> 2018 &copy; ULTRAmap OS</div>
</div>
