

<div id="sidebar"> <a href="#" class="visible-phone"><i class="icon icon-list"></i> Menu</a>
    <ul>


        <li class=""><a href=""><i class="icon icon-home"></i> <span>Dashboard</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/clientes"><i class="icon icon-group"></i> <span>Clientes</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/produtos"><i class="icon icon-barcode"></i> <span>Produtos</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/servicos"><i class="icon icon-wrench"></i> <span>Serviços</span></a></li>

        <li class="active"><a href="<?= base_url('') ?>/os"><i class="icon icon-tags"></i> <span>Ordens de Serviço</span></a></li>



        <li class="submenu ">
            <a href="#"><i class="icon icon-money"></i> <span>Financeiro</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="<?= base_url('') ?>/financeiro/lancamentos">Lançamentos</a></li>

            </ul>
        </li>
    </ul>
</div>



<div id="content">
    <div id="content-header">
        <div id="breadcrumb"> <a href="<?= base_url('') ?>/dashboard" title="Dashboard" class="tip-bottom"><i class="icon-home"></i> Dashboard</a> <a href="<?= base_url('') ?>/os" class="tip-bottom" title="Os">Os</a> <a href="<?= base_url('') ?>/os/editar?id=<?=$_GET['id']?>" class="current tip-bottom" title="Editar">Editar</a> </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">



                <style>
                    .imagegrayscale{
                        -webkit-filter:grayscale(100%);
                    }
                    .imagegrayscale:hover{
                        -webkit-filter:grayscale(0%);
                        transition: 1s;
                    }
                    /*O transition é apenas para dar um efeito mais suave. Você só deve levar em consideração
                    que deve usar o prefixo webkit para os navegadores chrome, safari e opera.
                    O firefox 35+ e o edge 16+ já suportam sem precisar usar prefixo.*/
                </style>
                <div id="desabilitarbody" style="width:100%; height:100%; position:fixed; background-color:rgba(0,0,0,0.50); z-index:5; display:none; "><p style="font-size:20px; color:rgba(255,253,253,1.00); padding:10px;">AGUARDE...</p></div>
                <div id="divnotificacoes2" style="width:50%; margin-top:0%; margin-left:10%; border-radius:20px; position:fixed; background-color:#FFFD00; padding:20px; display:none; z-index:10"><p onClick="fecharnotif()">X</p><div id="divnotificacoes"> </div>

                </div>
                <div>
                        <?= $this->AlertaHome();?>
                </div>
                <div class="row-fluid" style="margin-top:0;">
                    
                    <div class="span12">
                        
                        <div class="widget-box">
                            
                            <div class="widget-title">
                                <span class="icon">
                                    <i class="icon-tags"></i>
                                </span>
                                
                                <h5>Editar OS</h5>

                            </div>
                            <div class="widget-content nopadding">


                                <div class="span12" id="divProdutosServicos" style=" margin-left: 0">
                                    <ul class="nav nav-tabs">
                                        <li class="active" id="tabDetalhes"><a href="#tab1" data-toggle="tab">Detalhes da OS</a></li>
                                        <li id="tabProdutos"><a href="#tab2" data-toggle="tab">Produtos</a></li>
                                        <li id="tabServicos"><a href="#tab3" data-toggle="tab">Serviços</a></li>
                                    </ul>
                                    <div class="tab-content">
                                        <div class="tab-pane active" id="tab1">
                                            <div class="span12" id="divCadastrarOs">

                                                <form action="<?= base_url('') ?>/os/update/salvar" method="post" id="formOs">
                                                    <h3>Protocolo #1210</h3>
                                                    <?php foreach ($this->view->oneOs as $os) {
                                                        ?>

                                                        <div class="form-row">
                                                            <div class="form-group col-md-6">
                                                                <label for="cliente">Cliente*</label>
                                                                <input type="text" class="form-control" name="nomeCliente" value="<?= $os['nomeCliente'] ?>">
                                                                <input id="clientes_id" class="span12" type="hidden" name="idOs" value="<?= $os['idOs'] ?>"  />
                                                                <input id="clientes_id" class="span12" type="hidden" name="clientes_id" value="<?= $os['idClientes'] ?>"  />
                                                            </div>

                                                            <div class="form-group col-md-6">
                                                                <label for="tecnico">Técnico / Responsável*</label>
                                                                <select class="form-control" name="usuarios_id" id="usuarios_id" value="">                                                            
                                                                    <?php foreach ($this->view->allUsuario as $allUsuario) { ?>

                                                                        <option value="<?= $allUsuario['idUsuarios'] ?>">
                                                                            <?php echo $allUsuario['nome_usuario']; ?>
                                                                        </option>                                                            
                                                                    <?php } ?>

                                                                </select>
                                                            </div>
                                                        </div>


                                                        <div class="form-row">
                                                            <div class="form-group col-md-2">
                                                                <label for="status">Status<span class="required">*</span></label>
                                                                <select class="form-control" name="status" id="status" value="" >
                                                                    <option value="Orçamento">Orçamento</option>
                                                                    <option value="Aberto">Aberto</option>
                                                                    <option value="Em Andamento">Em Andamento</option>
                                                                    <option value="Finalizado">Finalizado</option>
                                                                    <option value="Cancelado">Cancelado</option>
                                                                </select>
                                                            </div>
                                                            <div class="form-group col-md-2">
                                                                <label for="dataInicial">Data Inicial<span class="required">*</span></label>
                                                                <input type="date" id="dataInicial" class="form-control datepicker"  name="dataInicial" value="<?= $os['dataInicial'] ?>" />
                                                            </div>
                                                            <div class="form-group col-md-2">
                                                                <label for="dataFinal">Data Final</label>
                                                                <input id="dataFinal" class="form-control datepicker" type="date" name="dataFinal" value="<?= $os['dataFinal'] ?>" />
                                                            </div>
                                                            <div class="form-group col-md-2">
                                                                <label for="telefone">Telefone</label>
                                                                <input id="telefone" class="form-control" type="tel" name="telefone" value="<?= $os['telefone'] ?>">
                                                            </div>
                                                            <div class="form-group col-md-2">
                                                                <label for="quantidade">Quantidade</label>
                                                                <input id="quantidade" class="form-control" type="number" name="quantidade" value="<?= $os['quantidade'] ?>">
                                                            </div>
                                                            <div class="form-group col-md-2">
                                                                <label for="cidade">Cidade</label>
                                                                <input id="cidade" class="form-control" type="text" name="cidade" value="<?= $os['cidade'] ?>">
                                                            </div>
                                                        </div>

                                                        <div class="row " style="margin-left: 15%;">                                                            
                                                            <div class="form-group col-md-10" >
                                                                <label for="descricaoServico" style="align-items:  center; margin-left: 40%;">Descrição Serviço</label>
                                                                <textarea class="form-control" name="descricaoServico" id="descricaoServico" cols="30" rows="5"><?= $os['descricaoServico'] ?></textarea>
                                                            </div> 
                                                        </div>

                                                    <?php } ?>
                                                    <div class="" style="padding: 0; margin-left: 0; margin-top: 15%; margin-bottom: 0;">
                                                        <div class="span6 offset3" style="text-align: center">
<!--                                                            <a href="#modal-faturar" id="btn-faturar" role="button" data-toggle="modal" class="btn btn-success" onClick="redefinir2();"><i class="icon-file"></i> Faturar</a>-->
                                                            <button class="btn btn-primary" id="btnContinuar"><i class="icon-white icon-ok"></i>Salvar</button>
                                                            <a href="<?= base_url('') ?>/os/visualizar?id=<?= $os['idOs'] ?>" class="btn btn-inverse"><i class="icon-eye-open"></i> Visualizar</a>
                                                            <a href="<?= base_url('') ?>/os" class="btn"><i class="icon-arrow-left"></i> Voltar</a>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>


                                        <!--Produtos-->
                                        <div class="tab-pane" id="tab2">
                                            <div class="span12" style="padding: 1%; margin-left: 0">
                                                <div class="span12 well" style="padding: 1%; margin-left: 0">
                                                    <form  action="<?= base_url("") ?>/os/salvarOsProduto" method="post">
                                                        <div class="span8"> 
                                                            <input type="hidden" name="os_id" id="idOsProduto" value="<?= $os['idOs'] ?>" />                                                        
                                                            <label for="">Produto</label>
                                                            <select class="span12" name="idProduto">

                                                                <?php foreach ($this->view->allProdutos as $allproduto) {
                                                                    ?>
                                                                    <option value="<?= $allproduto['idProduto'] ?>">
                                                                        <?php echo $allproduto['nome_produto']; ?>
                                                                    </option>                                                            
                                                                <?php } ?>

                                                            </select>

                                                        </div>
                                                        <div class="span2">
                                                            <label for="">Quantidade</label>
                                                            <input type="text" placeholder="Quantidade" id="quantidade" name="quantidade" class="span12" required />
                                                        </div>
                                                        <div class="span2">
                                                            <label for="">,</label>
                                                            <button class="btn btn-success span12" id="btnAdicionarProduto"><i class="icon-white icon-plus"></i> Adicionar</button>

                                                        </div>
                                                    </form>
                                                </div>


                                                <div class="span12" id="divProdutos" style="margin-left: 0">
                                                    <table class="table table-bordered" id="tblProdutos">
                                                        <thead>
                                                            <tr>
                                                                <th>Produto</th>
                                                                <th>Quantidade</th>
                                                                <th>Ações</th>
                                                                <th>Sub-total</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <?php
                                                            $total = 0;
                                                            foreach ($this->view->OsProduto as $oneProduto) {
                                                                $subTotal = $oneProduto['subTotal'];
                                                                $total = $total + $subTotal;
                                                                ?>
                                                                <tr>
                                                                    <td><?= $oneProduto['nome_produto'] ?></td>
                                                                    <td><?= $oneProduto['quantidade'] ?></td>
                                                                    <td><a href="<?= base_url('') ?>/os/oRemoverProduto?id=<?= $oneProduto['idProdutos_os'] ?>&idOs=<?= $os['idOs'] ?>"   title="Remover"  class="btn btn-danger"><i class="icon-remove icon-white"></i></a></td>
                                                                    <td><?= 'R$: ' . number_format($oneProduto['subTotal'], 2, ',', '.'); ?></td>
                                                                </tr>                                       
                                                                <tr>
                                                                <?php } ?>
                                                                <td colspan="3" style="text-align: right"><strong>Total:</strong></td>
                                                                <td><strong><div id="totalprodutos"><?= 'R$: ' . number_format($total, 2, ',', '.'); ?></div><input type="hidden" id="total-venda" value="100.00"></strong></td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>

                                        <!--Serviços-->
                                        <div class="tab-pane" id="tab3">
                                            <div class="span12" style="padding: 1%; margin-left: 0">
                                                <div class="span12 well" style="padding: 1%; margin-left: 0">

                                                    <form id="formServicoss" action="<?= base_url('') ?>/os/salvarOsServico" method="post">
                                                        <div class="span10">
                                                            <input type="hidden" name="os_id" id="idOsServico" value="<?= $os['idOs'] ?>" />                                                        
                                                            <label for="">Produto</label>
                                                            <select class="span12" name="idServicos">

                                                                <?php foreach ($this->view->allServicos as $allservico) {
                                                                    ?>
                                                                    <option value="<?= $allservico['idServicos'] ?>">
                                                                        <?php echo $allservico['nome_servico']; ?>
                                                                    </option>                                                            
                                                                <?php } ?>

                                                            </select>
                                                        </div>
                                                        <div class="span2">
                                                            <label for="">.</label>
                                                            <button class="btn btn-success span12"><i class="icon-white icon-plus"></i> Adicionar</button>
                                                        </div>
                                                    </form>
                                                </div>
                                                <div class="span12" id="divServicos" style="margin-left: 0">
                                                    <table class="table table-bordered">
                                                        <thead>
                                                            <tr>
                                                                <th>Serviço</th>
                                                                <th>Ações</th>
                                                                <th>Sub-total</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <?php
                                                            $total = 0;
                                                            foreach ($this->view->oneServicos as $oneservicos) {
                                                                $total = $total + $oneservicos['subTotal'];
                                                                ?>

                                                                <tr>
                                                                    <td><?= $oneservicos['nome_servico'] ?></td>

                                                                    <td><a href="<?= base_url('') ?>/os/oRemoverServico?id=<?= $oneservicos['idServicos_os'] ?>&idOs=<?= $os['idOs'] ?>"   title="Remover"  class="btn btn-danger"><i class="icon-remove icon-white"></i></a></td>
                                                                    <td><?= 'R$: ' . number_format($oneservicos['subTotal'], 2, ',', '.'); ?></td>
                                                                </tr>
                                                            <?php } ?>
                                                            <tr>
                                                                <td colspan="2" style="text-align: right"><strong>Total:</strong></td>
                                                                <td><strong><?= 'R$: ' . number_format($total, 2, ',', '.'); ?><input type="hidden" id="total-servico" value="0.00"></strong></td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        //Mascara para os inpust70645-160

        $("#celular").mask("(00) 0 0000-0000");
        $("#telefone").mask("(00) 0000-0000");
    });
</script>








