

<div id="sidebar"> <a href="#" class="visible-phone"><i class="icon icon-list"></i> Menu</a>
    <ul>


        <li class=""><a href=""><i class="icon icon-home"></i> <span>Dashboard</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/clientes"><i class="icon icon-group"></i> <span>Clientes</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/produtos"><i class="icon icon-barcode"></i> <span>Produtos</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/servicos"><i class="icon icon-wrench"></i> <span>Serviços</span></a></li>

        <li class="active"><a href="<?= base_url('') ?>/os"><i class="icon icon-tags"></i> <span>Ordens de Serviço</span></a></li>



        <li class="submenu ">
            <a href="#"><i class="icon icon-money"></i> <span>Financeiro</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="<?= base_url('')?>/financeiro/lancamentos">Lançamentos</a></li>
                
            </ul>
        </li>





        <li class="submenu ">
            <a href="#"><i class="icon icon-cog"></i> <span>Configurações</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="index.php/usuarios">Usuários</a></li>
                <li><a href="index.php/mapos/emitente">Emitente</a></li>
                <!--<li><a href="index.php/permissoes">Permissões</a></li>-->
                <!--<li><a href="index.php/mapos/backup">Backup</a></li>-->
                <!-- <li><a  href="#" title="configuraremail" onClick="abrirnotificacao(this)">Email(imap)</a></li>-->
                <li><a  href="#" title="configurarpagseguro.php" onClick="abrirnotificacao(this)">PagSeguro</a></li>
            </ul>
        </li>


    </ul>
</div>



<div id="content">
    <div id="content-header">
        <div id="breadcrumb"> <a href="<?= base_url('')?>" title="Dashboard" class="tip-bottom"><i class="icon-home"></i> Dashboard</a> <a href="<?= base_url('')?>/os" class="tip-bottom" title="Os">Os</a> <a href="<?= base_url('')?>/os/editar" class="current tip-bottom" title="Editar">Editar</a> </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">



                <style>
                    .imagegrayscale{
                        -webkit-filter:grayscale(100%);
                    }
                    .imagegrayscale:hover{
                        -webkit-filter:grayscale(0%);
                        transition: 1s;
                    }
                    /*O transition é apenas para dar um efeito mais suave. Você só deve levar em consideração
                    que deve usar o prefixo webkit para os navegadores chrome, safari e opera.
                    O firefox 35+ e o edge 16+ já suportam sem precisar usar prefixo.*/
                </style>
                <div id="desabilitarbody" style="width:100%; height:100%; position:fixed; background-color:rgba(0,0,0,0.50); z-index:5; display:none; "><p style="font-size:20px; color:rgba(255,253,253,1.00); padding:10px;">AGUARDE...</p></div>

                <link rel="stylesheet" href="https://www.ultramapos.online/js/jquery-ui/css/smoothness/jquery-ui-1.9.2.custom.css" />
                <script type="text/javascript" src="https://www.ultramapos.online/js/jquery-ui/js/jquery-ui-1.9.2.custom.js"></script>
                <script type="text/javascript" src="https://www.ultramapos.online/js/jquery.validate.js"></script>
                <div id="divnotificacoes2" style="width:50%; margin-top:0%; margin-left:10%; border-radius:20px; position:fixed; background-color:#FFFD00; padding:20px; display:none; z-index:10"><p onClick="fecharnotif()">X</p><div id="divnotificacoes"> </div>

                </div>




                <div class="row-fluid" style="margin-top:0">

                    <div class="span12">

<!--<input type="checkbox" checked id="notificacaoEmail" style="margin-top:-4px"> Notificação por Email | <input type="checkbox" disabled id="notificacaoSms" style="margin-top:-4px"> Notificação por SMS-->
                        <div class="widget-box">
                            <div class="widget-title">
                                <span class="icon">
                                    <i class="icon-tags"></i>
                                </span>
                                <h5>Editar OS</h5>
                                <?php
                                $this->alerta();
                                ?>
                            </div>
                            <div class="widget-content nopadding">


                                <div class="span12" id="divProdutosServicos" style=" margin-left: 0">
                                    <ul class="nav nav-tabs">
                                        <li class="active" id="tabDetalhes"><a href="#tab1" data-toggle="tab">Detalhes da OS</a></li>
                                        <li id="tabProdutos"><a href="#tab2" data-toggle="tab">Produtos</a></li>
                                        <li id="tabServicos"><a href="#tab3" data-toggle="tab">Serviços</a></li>
                                    </ul>
                                    <div class="tab-content">
                                        <div class="tab-pane active" id="tab1">

                                            <div class="span12" id="divCadastrarOs">

                                                <form action="<?= base_url('')?>/os/update/salvar" method="post" id="formOs">
                                                    <h3>Protocolo #1210</h3>
                                                    <?php foreach ($this->view->oneOs as $os) {
                                                        ?>
                                                        <div class="span12" style="padding: 1%; margin-left: 1%; ">
                                                            <div class="span6">
                                                                <label for="cliente">Cliente*</label>                                                                                                                          

                                                                <input type="text" name="nomeCliente" value="<?= $os['nomeCliente'] ?>">
                                                                <input id="clientes_id" class="span12" type="hidden" name="idOs" value="<?=$os['idOs']?>"  />
                                                                <input id="clientes_id" class="span12" type="hidden" name="clientes_id" value="<?=$os['idClientes']?>"  />
                                                            </div>
                                                            <div class="span6">
                                                                <label for="tecnico">Técnico / Responsável*</label>


                                                                <select class="span12" name="usuarios_id" id="usuarios_id" value="">                                                            
                                                                    <?php foreach ($this->view->allUsuario as $allUsuario) { ?>
                                                                    
                                                                        <option value="<?=$allUsuario['idUsuarios'] ?>">
                                                                            <?php echo $allUsuario['nome_usuario']; ?>
                                                                        </option>                                                            
                                                                    <?php } ?>

                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="span12" style="padding: 1%; margin-left: 1%;">
                                                            <div class="span2">
                                                                <label for="status">Status<span class="required">*</span></label>
                                                                <select class="span12" name="status" id="status" value="" >
                                                                    <option value="Orçamento">Orçamento</option>
                                                                    <option value="Aberto">Aberto</option>
                                                                    <option value="Em Andamento">Em Andamento</option>
                                                                    <option value="Finalizado">Finalizado</option>
                                                                    <option value="Cancelado">Cancelado</option>
                                                                </select>
                                                            </div>
                                                            <div class="span2">
                                                                <label for="dataInicial">Data Inicial<span class="required">*</span></label>
                                                                <input type="date" id="dataInicial" class="span12 datepicker"  name="dataInicial" value="<?= $os['dataInicial'] ?>" />
                                                            </div>
                                                            <div class="span2">
                                                                <label for="dataFinal">Data Final</label>
                                                                <input id="dataFinal" class="span12 datepicker" type="date" name="dataFinal" value="<?= $os['dataFinal'] ?>" />
                                                            </div>
                                                            <div class="span2">
                                                                <label for="telefone">Telefone</label>
                                                                <input id="telefone" class="span12" type="tel" name="telefone" value="<?= $os['telefone'] ?>">
                                                            </div>
                                                            <div class="span1">
                                                                <label for="quantidade">Quantidade</label>
                                                                <input id="quantidade" class="span12" type="number" name="quantidade" value="<?= $os['quantidade'] ?>">
                                                            </div>
                                                            <div class="span3">
                                                                <label for="cidade">Cidade</label>
                                                                <input id="cidade" class="span8" type="text" name="cidade" value="<?= $os['cidade'] ?>">
                                                            </div>


                                                        </div>

                                                        <div class="span12" style="padding: 1%; margin-left: 0">
                                                            <div class="span12" style="padding: 1%; margin-left: 0">
                                                                <div class="span6">
                                                                    <label for="descricaoServico">Descrição Serviço</label>
                                                                    <textarea class="span12" name="descricaoServico" id="descricaoServico" cols="30" rows="5"><?= $os['descricaoServico'] ?></textarea>
                                                                </div>                                                                
                                                            </div>

                                                        </div>
                                                    <?php } ?>
                                                    <div class="span12" style="padding: 1%; margin-left: 0">
                                                        <div class="span6 offset3" style="text-align: center">
                                                            <a href="#modal-faturar" id="btn-faturar" role="button" data-toggle="modal" class="btn btn-success" onClick="redefinir2();"><i class="icon-file"></i> Faturar</a>
                                                            <button class="btn btn-primary" id="btnContinuar"><i class="icon-white icon-ok"></i>Salvar</button>
                                                            <a href="<?= base_url('') ?>/os/visualizar?id=" class="btn btn-inverse"><i class="icon-eye-open"></i> Visualizar</a>
                                                            <a href="<?= base_url('') ?>/os" class="btn"><i class="icon-arrow-left"></i> Voltar</a>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>

                                        </div>


                                        <!--Produtos-->
                                        <div class="tab-pane" id="tab2">
                                            <div class="span12 well" style="padding: 1%; margin-left: 0">
                                                <form  action="<?= base_url("") ?>/os/salvarOsProduto" method="post">
                                                    <div class="span8"> 
                                                        <input type="hidden" name="os_id" id="idOsProduto" value="<?= $os['idOs'] ?>" />                                                        
                                                        <label for="">Produto</label>
                                                        <select class="span12" name="idProduto">

                                                            <?php foreach ($this->view->allProdutos as $allproduto) { ?>
                                                                <option value="<?= $allproduto['idProduto'] ?>">
                                                                    <?php echo $allproduto['nome_produto']; ?>
                                                                </option>                                                            
                                                            <?php } ?>

                                                        </select>

                                                    </div>
                                                    <div class="span2">
                                                        <label for="">Quantidade</label>
                                                        <input type="text" placeholder="Quantidade" id="quantidade" name="quantidade" class="span12" required />
                                                    </div>
                                                    <div class="span2">
                                                        <label for="">,</label>
                                                        <button class="btn btn-success span12" id="btnAdicionarProduto"><i class="icon-white icon-plus"></i> Adicionar</button>

                                                    </div>
                                                </form>
                                            </div>
                                            <div class="span12" id="divProdutos" style="margin-left: 0">
                                                <table class="table table-bordered" id="tblProdutos">
                                                    <thead>
                                                        <tr>
                                                            <th>Produto</th>
                                                            <th>Quantidade</th>
                                                            <th>Ações</th>
                                                            <th>Sub-total</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <?php
                                                        $total = 0;
                                                        foreach ($this->view->oneProdutos as $oneProduto) {
                                                            $subTotal = $oneProduto['subTotal'];
                                                            $total = $total + $subTotal;
                                                            ?>
                                                            <tr>
                                                                <td><?= $oneProduto['nome_produto'] ?></td>
                                                                <td><?= $oneProduto['quantidade'] ?></td>
                                                                <td><a href="<?= base_url('') ?>/os/oRemoverProduto?id=<?= $oneProduto['idProdutos_os'] ?>&idOs=<?= $os['idOs'] ?>"   title="Remover"  class="btn btn-danger"><i class="icon-remove icon-white"></i></a></td>
                                                                <td><?= $oneProduto['subTotal'] ?></td>
                                                            </tr>                                       
                                                            <tr>
                                                            <?php } ?>
                                                            <td colspan="3" style="text-align: right"><strong>Total:</strong></td>
                                                            <td><strong><div id="totalprodutos"><?= $total ?></div><input type="hidden" id="total-venda" value="100.00"></strong></td>
                                                        </tr>

                                                    </tbody>
                                                </table>
                                            </div>

                                        </div>

                                        <!--Serviços-->
                                        <div class="tab-pane" id="tab3">
                                            <div class="span12" style="padding: 1%; margin-left: 0">
                                                <div class="span12 well" style="padding: 1%; margin-left: 0">

                                                    <form id="formServicoss" action="<?= base_url('') ?>/os/salvarOsServico" method="post">
                                                        <div class="span10">
                                                            <input type="hidden" name="os_id" id="idOsServico" value="<?= $os['idOs'] ?>" />                                                        
                                                            <label for="">Produto</label>
                                                            <select class="span12" name="idServicos">

                                                                <?php foreach ($this->view->allServicos as $allservico) {
                                                                    ?>
                                                                    <option value="<?= $allservico['idServicos'] ?>">
                                                                        <?php echo $allservico['nome_servico']; ?>
                                                                    </option>                                                            
                                                                <?php } ?>

                                                            </select>
                                                        </div>
                                                        <div class="span2">
                                                            <label for="">.</label>
                                                            <button class="btn btn-success span12"><i class="icon-white icon-plus"></i> Adicionar</button>
                                                        </div>
                                                    </form>
                                                </div>
                                                <div class="span12" id="divServicos" style="margin-left: 0">
                                                    <table class="table table-bordered">
                                                        <thead>
                                                            <tr>
                                                                <th>Serviço</th>
                                                                <th>Ações</th>
                                                                <th>Sub-total</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <?php
                                                            $total = 0;
                                                            foreach ($this->view->oneServicos as $oneservicos) {
                                                                $total = $total + $oneservicos['subTotal'];
                                                                ?>

                                                                <tr>
                                                                    <td><?= $oneservicos['nome_servico'] ?></td>

                                                                    <td><a href="<?= base_url('') ?>/os/oRemoverServico?id=<?= $oneservicos['idServicos_os'] ?>&idOs=<?= $os['idOs'] ?>"   title="Remover"  class="btn btn-danger"><i class="icon-remove icon-white"></i></a></td>
                                                                    <td><?= $oneservicos['subTotal'] ?></td>
                                                                </tr>
                                                            <?php } ?>
                                                            <tr>
                                                                <td colspan="2" style="text-align: right"><strong>Total:</strong></td>
                                                                <td><strong><?= $total ?><input type="hidden" id="total-servico" value="0.00"></strong></td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>

                                            </div>
                                        </div>


                                        <!--Anexos-->


                                        <!-- Modal Faturar-->
                                        <div id="modal-faturar" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="width:76%; height:76%; max-width:700px;  margin-left:-30%" >
                                            <form id="formFaturar" action="/editarOs.php" method="post">

                                                <!--para no android funcionar o faturamento tem que ter este form aqui, eu eim!!!-->
                                            </form>




                                            <form id="formFaturarr" action="" method="post">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                    <h3 id="myModalLabel">Faturar Vendass</h3>
                                                </div>
                                                <div class="modal-body">

                                                    <div class="span12 alert alert-info" style="margin-left: 0"> Obrigatório o preenchimento dos campos com asterisco.</div>
                                                    <div class="span12" style="margin-left: 0"> 
                                                        <label for="descricao">Descrição</label>
                                                        <input class="span12" id="descricao" required type="text" name="descricao" value="Fatura da OS N. - #104 "  />

                                                    </div>  
                                                    <div class="span12" style="margin-left: 0"> 
                                                        <div class="span12" style="margin-left: 0"> 
                                                            <label for="cliente">Cliente*</label>
                                                            <input class="span12" id="cliente" type="text" name="cliente" required value="wesllen" />
                                                            <input type="hidden" name="clientes_id" id="clientes_id" value="84">
                                                            <input type="hidden" name="os_id" id="os_id" value="104">
                                                        </div>


                                                    </div>
                                                    <div class="span12" style="margin-left: 0"> 
                                                        <div class="span4" style="margin-left: 0">  
                                                            <label for="valor">Valor*</label>
                                                            <input type="hidden" id="tipo" name="tipo" value="receita" /> 
                                                            <input class="span12" id="valor" type="number" step="0.01" name="valor" value="0.00"  onChange="document.getElementById('desconto').value = '0';
                                                                    valortotal = document.getElementById('valor').value;
                                                                    parcelasF();" onFocus="recuperarvalortotal()"/>
                                                        </div>

                                                        <div class="span4" style="margin-left: 0">  
                                                            <label for="desconto">Desconto (%)</label>
                                                            <input type="hidden" id="tipo" name="tipo" value="desconto" /> 
                                                            <input class="span12" id="desconto" type="number" name="desconto" value="0"  onChange="fdesconto()" onFocus="recuperarvalortotal()" />
                                                            <br>
                                                        </div>

                                                        <div class="span4" style="margin-left: 0;">  
                                                            <label for="parcelas">Parcelas(Boleto)</label>
                                                            <select name="parcelas" id="parcelas" onChange="parcelasF()" onFocus="recuperarvalortotal()" >
                                                                <option value="-">-</option>
                                                                <option value="1">1</option>
                                                                <option value="2">2</option>
                                                                <option value="3">3</option>
                                                                <option value="4" disabled>4</option>
                                                                <option value="5" disabled>5</option>
                                                                <option value="6" disabled>6</option>
                                                                <option value="7" disabled>7</option>
                                                                <option value="8" disabled>8</option>
                                                                <option value="9" disabled>9</option>
                                                                <option value="10" disabled>10</option>
                                                            </select> <p id="valorporparcela">error !!!</p>
                                                            <br>
                                                        </div>
                                                        <div class="span4">
                                                            <label for="vencimento" id="datavencimentoprimeiro">Data Vencimento*</label>
                                                            <input class="span12" id="vencimento" type="date" name="vencimento" value="2018-06-19" required/>
                                                        </div>

                                                    </div>

                                                    <div class="span12" style="margin-left: 0"> 
                                                        <div class="span4" style="margin-left: 0" id="divrecebido">
                                                            <label for="recebido">Recebido?</label>
                                                            &nbsp &nbsp &nbsp &nbsp <input  id="recebido" type="checkbox" name="recebido" value="3" /> 
                                                        </div>
                                                        <div id="divRecebimento" class="span8" style=" display: none">
                                                            <div class="span6">
                                                                <label for="recebimento">Data Recebimento</label>
                                                                <input class="span12" id="recebimento" type="date" name="recebimento" value='2018-06-19'/> 
                                                            </div>

                                                            <div class="span6">
                                                                <label for="formaPgto" >Forma Pgto</label>
                                                                <select name="formaPgto" id="formaPgto" class="span12" onChange="aparecetaxa();">
                                                                    <option value="Dinheiro">Dinheiro</option>
                                                                    <option value="Cartão de Crédito">Cartão de Crédito</option>
                                                                    <option value="Cheque">Cheque</option>
                                                                    <option value="Boleto">Boleto</option>
                                                                    <option value="Depósito">Depósito</option>
                                                                    <option value="Débito">Débito</option>        
                                                                </select>

                                                            </div>

                                                            <div   class="span4" style="display:none" id="divparcelasc">
                                                                <label for="parcelasc">Parcelas(cartão)</label>
                                                                <select name="parcelasc" id="parcelasc" class="span12" onChange="setartaxaparcela(this)" disabled>
                                                                    <option value="0">-</option>
                                                                    <option value="p1">1 parcela</option>
                                                                    <option value="p2">2 parcelas</option>
                                                                    <option value="p3">3 parcelas</option>
                                                                    <option value="p4">4 parcelas</option>
                                                                    <option value="p5">5 parcelas</option>
                                                                    <option value="p6">6 parcelas</option> 
                                                                    <option value="p7">7 parcelas</option> 
                                                                    <option value="p8">8 parcelas</option>
                                                                    <option value="p9">9 parcelas</option>
                                                                    <option value="p10">10 parcelas</option>
                                                                    <option value="p11">11 parcelas</option>
                                                                    <option value="p12">12 parcelas</option>
                                                                </select>
                                                            </div>  

                                                            <div class="span6" id="divtaxa" style="display:none">



                                                                <label for="taxa">Taxa do cartão (%)</label>
                                                                <input class="span12" id="taxa" type="number" name="taxa" disabled placeholder='Desabilitado'/> 

                                                            </div>

                                                        </div>


                                                    </div>


                                                    <div class="modal-footer">


                                                        <button class="btn" data-dismiss="modal" aria-hidden="true" id="btn-cancelar-faturar">Cancelar</button>
                                                        <button class="btn btn-primary">Faturar</button>
                                                    </div>

                                            </form>

                                        </div>

                                        <script type="text/javascript" src="https://www.ultramapos.online/js/jquery.validate.js"></script>
                                        <script src="https://www.ultramapos.online/js/maskmoney.js"></script>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        <script>
                                                                    $(document).ready(function () {
                                                                        //Mascara para os inpust70645-160

                                                                        $("#celular").mask("(00) 0 0000-0000");
                                                                        $("#telefone").mask("(00) 0000-0000");
                                                                    });
                        </script>








