
<div id="sidebar"> <a href="#" class="visible-phone"><i class="icon icon-list"></i> Menu</a>
    <ul>


        <li class=""><a href="<?= base_url('') ?>/dashboard"><i class="icon icon-home"></i> <span>Dashboard</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/clientes"><i class="icon icon-group"></i> <span>Clientes</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/produtos"><i class="icon icon-barcode"></i> <span>Produtos</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/servicos"><i class="icon icon-wrench"></i> <span>Serviços</span></a></li>

        <li class="active"><a href="<?= base_url('') ?>/os"><i class="icon icon-tags"></i> <span>Ordens de Serviço</span></a></li>

       


        <li class="submenu ">
            <a href="#"><i class="icon icon-money"></i> <span>Financeiro</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="<?= base_url('')?>/financeiro/lancamentos">Lançamentos</a></li>                
            </ul>
        </li>


        


        <li class="submenu ">
            <a href="#"><i class="icon icon-cog"></i> <span>Configurações</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="index.php/usuarios">Usuários</a></li>
                <li><a href="index.php/mapos/emitente">Emitente</a></li>
                <!--<li><a href="index.php/permissoes">Permissões</a></li>-->
                <!--<li><a href="index.php/mapos/backup">Backup</a></li>-->
                <!-- <li><a  href="#" title="configuraremail" onClick="abrirnotificacao(this)">Email(imap)</a></li>-->
                <li><a  href="#" title="configurarpagseguro.php" onClick="abrirnotificacao(this)">PagSeguro</a></li>
            </ul>
        </li>


    </ul>
</div>

<div id="content">
    <div id="content-header">
        <?= $this->AlertaHome();?> 
        <div id="breadcrumb"> <a href="<?= base_url('')?>" title="Dashboard" class="tip-bottom"><i class="icon-home"></i> Dashboard</a> <a href="<?= base_url('')?>/os" class="tip-bottom" title="Os">Os</a></div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="container-fluid col-sm-5  nopadding" style="margin-left: 3%;">
                    </div>

                <script>document.cookie = "resolucao=" + screen.width;</script>

                <div class="span12" style="margin-left: 0">
                    <form method="get" action="">
                        <div class="span3">
                            <a href="<?php base_url('')?>/os/adicionar" class="btn btn-success span12"><i class="icon-plus icon-white"></i> Adicionar OS</a>
                        </div>
                        <div class="span3">
                            <input type="text" name="nome"  id="pesquisa"  placeholder="Nome do cliente" class="span12" value="" >
                        </div>
                        <div class="span2">
                            <select name="status" id="status" class="span12">
                                <option value="">Selecione status</option>
                                <option value="Orçamento">Orçamento</option>
                                <option value="Aberto">Aberto</option>              
                                <option value="Em Andamento">Em Andamento</option>
                                <option value="Aguardando Retirada">Aguardando Retirada</option>
                                <option value="Faturado">Faturado</option>
                                <option value="Finalizado">Finalizado</option>
                                <option value="Cancelado">Cancelado</option>
                            </select>

                        </div>

                        <div class="span3">
                            <input type="text" name="data"  id="data"  placeholder="Data Inicial" class="span6 datepicker" value="">
                            <input type="text" name="data2"  id="data2"  placeholder="Data Final" class="span6 datepicker" value="" >
                        </div>
                        <div class="span1">
                            <button class="span12 btn"> <i class="icon-search"></i> </button>
                        </div>
                    </form>
                </div>



                <div class="widget-box">
                    <div class="widget-title">
                        <span class="icon">
                            <i class="icon-tags"></i>
                        </span>
                        <h5>Ordens de Serviço</h5>

                    </div>

                    <div class="widget-content nopadding">


                        <table class="table table-bordered ">
                            <thead>
                                <tr style="backgroud-color: #2D335B">
                                    <th>#</th>
                                    <th>Cliente</th>
                                    <th>Responsável</th>
                                    <th>Data Inicial</th>
                                    <th>Data Final</th>
                                    <th>Status</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <?php
                            $total = 0;
                            foreach ($this->view->os as $linha) {
                            $id = count(['idOs']);
                            $total = $total + $id;
                            }
                            if ($total > 0) {?>
                            <tbody>
                                        <?php foreach ($this->view->os as $linha) { ?>
                            <tr>
                                <td><?=$linha['idOs']?></td>
                                <td><?=$linha['nomeCliente']?></td>
                                <td><?=$linha['nome_usuario']?></td>
                                <td><?=$linha['dataInicial']?></td>
                                <?php
                                            $data = "0000-00-00";
                                            $dataFinal = $linha['dataFinal'];
                                             if(strtotime($data) == strtotime($dataFinal)){
                                                 echo '<td>Data Ainda não informada</td>';
                                             } else {
                                                  echo "<td>". date('d/m/Y', strtotime($linha['dataFinal']))."</td>";
                                             }       
                                                    
                                            ?>                                            

                                <td><span class = "badge" style = "background-color: #CDB380; border-color: #CDB380"><?=$linha['status_pedido']?></span> </td>
                                <td>
                                    <a style = "margin-right: 1%" href = "<?= base_url('') ?>/os/visualizar?id=<?= $linha['idOs'] ?>" class = "btn tip-top" title = "Ver mais detalhes"><i class = "icon-eye-open"></i></a>                                    
                                    <a style = "margin-right: 1%" href = "<?= base_url('')?>/os/editar?id=<?= $linha['idOs'] ?>" class = "btn btn-info tip-top" title = "Editar OS"><i class = "icon-pencil icon-white"></i></a>
                                    <a style="margin-right: 1%" class="btn btn-danger tip-top" title="Excluir Cliente" data-toggle="modal" data-target="#exampleModal" data-whatever="<?= $linha['idOs'] ?>"><i class="icon-remove icon-white"></i></a>
                                </td>
                            </tr> 
                            
                            <?php
                            
                                } 
                            ?>

                            </tbody>
                            <?php
                                } else {
                                    ?>
                                    <tbody>
                                        <tr>
                                            <td colspan = "5">Nenhum Cliente Cadastrado</td>
                                        </tr>
                                    </tbody>
                                    <?php
                                }
                                ?>
                                    <!-- Modal  Excluir Cliente--> 
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title">Excluir clientes</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <form action="<?= base_url('') ?>/os/remover" method="POST">
                                                    <h3 style="text-align: center">Deseja realmente excluir este cliente ?</h3>
                                                    <div class="form-group">            
                                                        <input type="hidden" class="form-control" id="recipient-name" name="id" value="">
                                                    </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                                <button type="submit" class="btn btn-danger">Excluir</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </table>
                            </div>
                            </div>



                            






                            <script type = "text/javascript">
                            //script para passar o id para modal de excluir
                        $('#exampleModal').on('show.bs.modal', function (event) {
                            var button = $(event.relatedTarget) // Button that triggered the modal
                            var recipient = button.data('whatever') // Extract info from data-* attributes
                            // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
                            // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
                            var modal = $(this)

                            modal.find('.modal-body input').val(recipient)
                        });    
                                
                            $(document).ready(function(){


                            $(document).on('click', 'a', function(event) {

                            var os = $(this).attr('os');
                            $('#idOs').val(os);

                            });

                            });

                            </script>


                    </div>
                </div>
            </div>
        </div>