
<div id="sidebar"> <a href="#" class="visible-phone"><i class="icon icon-list"></i> Menu</a>
    <ul>


        <li class=""><a href=""><i class="icon icon-home"></i> <span>Dashboard</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/clientes"><i class="icon icon-group"></i> <span>Clientes</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/produtos"><i class="icon icon-barcode"></i> <span>Produtos</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/servicos"><i class="icon icon-wrench"></i> <span>Serviços</span></a></li>

        <li class="active"><a href="<?= base_url('') ?>/os"><i class="icon icon-tags"></i> <span>Ordens de Serviço</span></a></li>



        <li class="submenu ">
            <a href="#"><i class="icon icon-money"></i> <span>Financeiro</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="<?= base_url('') ?>/financeiro/lancamentos">Lançamentos</a></li>                
            </ul>
        </li>





<!--        <li class="submenu ">
            <a href="#"><i class="icon icon-cog"></i> <span>Configurações</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="index.php/usuarios">Usuários</a></li>
                <li><a href="index.php/mapos/emitente">Emitente</a></li>
                <li><a href="index.php/permissoes">Permissões</a></li>
                <li><a href="index.php/mapos/backup">Backup</a></li>
                 <li><a  href="#" title="configuraremail" onClick="abrirnotificacao(this)">Email(imap)</a></li>
                <li><a  href="#" title="configurarpagseguro.php" onClick="abrirnotificacao(this)">PagSeguro</a></li>
            </ul>
        </li>-->


    </ul>
</div>

<div id="content" style="font-size: 15px;">
    <div id="content-header">
        <div id="breadcrumb"> <a href="<?= base_url('') ?>" title="Dashboard" class="tip-bottom"><i class="icon-home"></i> Dashboard</a> <a href="<?= base_url('') ?>/os" class="tip-bottom" title="Os">Os</a> <a href="<?= base_url('') ?>/os/visualizar" class="current tip-bottom" title="Visualizar">Visualizar</a> </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">


                <div class="row-fluid" style="margin-top: 0">
                    <div class="span12">
                        <div class="widget-box">
                            <div class="widget-title">
                                <span class="icon">
                                    <i class="icon-tags"></i>
                                </span>
                                <h5>Ordem de Serviço</h5>
                                <div class="buttons">
                                    <?php foreach ($this->view->os as $os) { ?>
                                    <a style="position: relative; margin-top: -7.6px;" title="Icon Title" class="btn btn-mini btn-info" href="<?= base_url('') ?>/os/editar?id=<?= $os['idOs'] ?>"><i class="icon-pencil icon-white"></i> Editar</a>                    
                                        
                                    <?php } ?>
                                </div>
                            </div>
                            <div class="widget-content" id="printOs">
                                <div class="invoice-content">
                                    <div class="invoice-head" style="margin-bottom: 0">

                                        <table class="table">

                                        </table>


                                        <table class="table">
                                            <tbody>
                                                <tr>
                                                    <td style="width: 50%; padding-left: 2%;">
                                                        <ul>
                                                            <li>
                                                                <?php foreach ($this->view->os as $os) { ?>
                                                                    <span><h5>Cliente</h5></span>
                                                                    <span><?= $os['nomeCliente'] ?></span><br/>
                                                                    <span><?= $os['rua'] ?> <?= $os['bairro'] ?> </span><br/>
                                                                    <span> <?= $os['cidade'] ?>- <?= $os['estado'] ?> CEP:<?= $os['cep'] ?></span><br>Tel.:  <?= $os['telefone'] ?> / <?= $os['celular'] ?> 

                                                                </li>
                                                            </ul>
                                                        </td>
                                                        <td style="width: 50%; padding-left: 0">
                                                            <ul>
                                                                <li>
                                                                    <span><h5>Responsável</h5></span>
                                                                    <span><?= $os['nome_usuario'] ?></span> <br/>                                                
                                                                </li>
                                                            </ul>

                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table> 

                                        </div>

                                        <div style="margin-top: 0; padding-top: 0">
                                            
                                            <hr style="margin-top: 0">
                                            <hr>
                                            <h5>Descrição</h5>
                                            <p>
                                                <?= $os['descricaoServico'] ?>                         
                                            </p>                                            
                                            <hr>
                                            <table class="table table-bordered" id="tblProdutos">
                                                <thead>
                                                    <tr>
                                                        <th>Produto</th>
                                                        <th>Quantidade</th>
                                                        <th>Sub-total</th>
                                                    </tr>
                                                </thead>
                                                <tbody>

                                                    <?php
                                                    $totalProduto = 0;
                                                    foreach ($this->view->oneProdutos as $oneProduto) {
                                                        $totalProduto = $totalProduto + $oneProduto['subTotal']
                                                        ?>
                                                        <tr>
                                                            <td><?= $oneProduto['nome_produto'] ?></td>
                                                            <td><?= $oneProduto['quantidade'] ?></td>
                                                            <td><?= $oneProduto['subTotal'] ?></td>
                                                        </tr>
    <?php } ?>


                                                    <tr>
                                                        <td colspan="2" style="text-align: right"><strong>Total:</strong></td>
                                                        <td><strong>R$ <?= $totalProduto ?></strong></td>
                                                    </tr>
                                                </tbody>
                                            </table>

                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr>
                                                        <th>Serviço</th>
                                                        <th>Sub-total</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php
                                                    $totalServic = 0;
                                                    foreach ($this->view->oneServico as $servico) {
                                                        $totalServic = $totalServic + $servico['preco'];
                                                        ?>
                                                        <tr>
                                                            <td><?= $servico['nome_servico'] ?></td>
                                                            <td>R$ <?= $servico['preco'] ?></td>
                                                        </tr>
    <?php } ?>

                                                    <tr>
                                                        <td colspan="1" style="text-align: right"><strong>Total:</strong></td>
                                                        <td><strong>R$ <?= $totalServic ?></strong></td>
                                                    </tr>
                                                </tbody>
                                            </table><?php } ?>
                                        <hr /><?php $total = $totalProduto + $totalServic; ?>
                                        <h4 style="text-align: right">Valor Total: R$ <?= $total ?></h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
