
<div id="sidebar"> <a href="#" class="visible-phone"><i class="icon icon-list"></i> Menu</a>
    <ul>


        <li class=""><a href=""><i class="icon icon-home"></i> <span>Dashboard</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/clientes"><i class="icon icon-group"></i> <span>Clientes</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/produtos"><i class="icon icon-barcode"></i> <span>Produtos</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/servicos"><i class="icon icon-wrench"></i> <span>Serviços</span></a></li>

        <li class="active"><a href="<?= base_url('') ?>/os"><i class="icon icon-tags"></i> <span>Ordens de Serviço</span></a></li>

        <li class=""><a href="<?= base_url('') ?>/vendas"><i class="icon icon-shopping-cart"></i> <span>Vendas</span></a></li>

        <li class=""><a href="arquivos.php"><i class="icon icon-hdd"></i> <span>Arquivos</span></a></li>


        <li class=""><a href="#" title="faleconosco.php" onClick="abrirnotificacao(this)"><i class="icon icon-hdd"></i> <span>Fale Conosco</span></a></li>

        <li class="submenu ">
            <a href="#"><i class="icon icon-money"></i> <span>Financeiro</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="index.php/financeiro/lancamentos">Lançamentos</a></li>
                <li><a title="recibo.php" onClick="abrirnotificacao(this)" style="cursor:pointer">Recibo</a></li>
                <li><a title="taxascartao.php?plano=1" onClick="abrirnotificacao(this)" style="cursor:pointer">Conf. Taxas cartão</a></li>       
            </ul>
        </li>


        <li class="submenu " >
            <a href="#"><i class="icon icon-list-alt"></i> <span>Relatórios</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>

                <li><a href="index.php/relatorios/clientes">Clientes</a></li>
                <li><a href="/./LayoutFabrica/relatorios/produtos.php">Produtos</a></li>
                <li><a href="/./LayoutFabrica/relatorios/servicos.php">Serviços</a></li>
                <li><a href="/./LayoutFabrica/relatorios/os.php">Ordens de Serviço</a></li>
                <li><a href="/./LayoutFabrica/relatorios/vendas.php">Vendas(Clientes)</a></li>
                <li><a title="consultarVendas.php?cache=1" onClick="abrirnotificacao(this)" style="cursor:pointer">vendas(itens)</a></li> 
                <li><a href="index.php/relatorios/financeiro">Financeiro</a></li>

            </ul>
        </li>


        <li class="submenu ">
            <a href="#"><i class="icon icon-cog"></i> <span>Configurações</span> <span class="label"><i class="icon-chevron-down"></i></span></a>
            <ul>
                <li><a href="index.php/usuarios">Usuários</a></li>
                <li><a href="index.php/mapos/emitente">Emitente</a></li>
                <!--<li><a href="index.php/permissoes">Permissões</a></li>-->
                <!--<li><a href="index.php/mapos/backup">Backup</a></li>-->
                <!-- <li><a  href="#" title="configuraremail" onClick="abrirnotificacao(this)">Email(imap)</a></li>-->
                <li><a  href="#" title="configurarpagseguro.php" onClick="abrirnotificacao(this)">PagSeguro</a></li>
            </ul>
        </li>


    </ul>
</div>

<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="https://www.ultramapos.online/" title="Dashboard" class="tip-bottom"><i class="icon-home"></i> Dashboard</a> <a href="https://www.ultramapos.online/index.php/os" class="tip-bottom" title="Os">Os</a> <a href="https://www.ultramapos.online/index.php/os/visualizar/103" class="current tip-bottom" title="Visualizar">Visualizar</a> </div>
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
          
                                                
                      <div class="row-fluid" style="margin-top: 0">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-tags"></i>
                </span>
                <h5>Ordem de Serviço</h5>
                <div class="buttons">
                    <a title="Icon Title" class="btn btn-mini btn-info" href="https://www.ultramapos.online/index.php/os/editar/103"><i class="icon-pencil icon-white"></i> Editar</a>                    
                    <a target="_blank" title="Imprimir" class="btn btn-mini btn-inverse" href="https://www.ultramapos.online/index.php/os/imprimir/103"><i class="icon-print icon-white"></i> Imprimir</a>
                </div>
            </div>
            <div class="widget-content" id="printOs">
                <div class="invoice-content">
                    <div class="invoice-head" style="margin-bottom: 0">

                        <table class="table">
                            <tbody>
                                                                <tr>
                                    <td style="width: 25%"><img src=" https://www.ultramapos.online/assets/uploads/b5502aef1fb4ae9096913b92a4626b61.jpg "></td>
                                    <td> <span style="font-size: 20px; "> pessoa fisica</span> </br><span>1221111 </br> apartamento, 12 - cruzeiro - brasilia - DF </span> </br> <span> E-mail: wesllenalves@gmail.com - Fone: 61981745695</span></td>
                                    <td style="width: 18%; text-align: center">#Protocolo: <span >103</span></br> </br> <span>Emissão: 16/06/2018</span></td>
                                </tr>

                                                            </tbody>
                        </table>

                
                        <table class="table">
                            <tbody>
                                <tr>
                                    <td style="width: 50%; padding-left: 0">
                                        <ul>
                                            <li>
                                                <span><h5>Cliente</h5>
                                                <span>wesllen</span><br/>
                                                <span>, </span><br/>
                                                <span> - DF</span><br>Tel.:  | 981745695                                            </li>
                                        </ul>
                                    </td>
                                    <td style="width: 50%; padding-left: 0">
                                        <ul>
                                            <li>
                                                <span><h5>Responsável</h5></span>
                                                <span>wesllen alves teste de cadastro</span> <br/>
                                                <span>Telefone: 61981745695</span><br/>
                                                <span>Email: wesllenalves@gmail.com</span>
                                            </li>
                                        </ul>
                                    </td>
                                </tr>
                            </tbody>
                        </table> 
      
                    </div>

                    <div style="margin-top: 0; padding-top: 0">

                    
                                                            
                                                
                                                <hr />
                    
                        <h4 style="text-align: right">Valor Total: R$ 0,00</h4>

                    </div>
            

                    
                    
              
                </div>
            </div>
        </div>
    </div>
</div>


      </div>
    </div>
  </div>
</div>
