

<div id="section1" class="container-fluid">
    <div class="col-md-4 offset-md-4">
        <!--<h1>Sessão 1</h1>
        <p>Clique nos diferentes links da Seção na barra de navegação</p>-->
    </div>
</div>

<div id="section2" class="container-fluid">
    <center>
        
        <div class="sectionint">
            <h1>Sessão 2</h1>
            <p>Clique nos diferentes links da Seção na barra de navegação</p>
            <input type="text" class="form-control" ng-model="nome">
            {{nome}}
        </div>
    </center>
</div>
<div id="section3" class="container-fluid">
    <center>
        <div class="sectionint">
            <h1>Sessão 3</h1>
            <p>Clique nos diferentes links da Seção na barra de navegação</p>
        </div>
    </center>
</div>
<div id="section4" class="container-fluid">
    <center>
        <div class="sectionint">
            <h1>Sessão 4</h1>
            <p>Clique nos diferentes links da Seção na barra de navegação</p>
        </div>
    </center>
</div>
<div id="section5" class="container-fluid">
    <center>
        <div class="sectionint">
            <h1>Sessão 5</h1>
            <p>Clique nos diferentes links da Seção na barra de navegação</p>
        </div>
    </center>
</div>
<div id="section6" class="container-fluid">
    <center>
        <div class="sectionint">
            <h1>Sessão 6</h1>
            <p>Clique nos diferentes links da Seção na barra de navegação</p>
        </div>
    </center>
</div>
<div id="footer">
    <footer class="footer">
        <div class="container-fluid">
            <nav class="pull-left">
                <ul>
                    <li>
                        <a href="#">
                            FabricadeSoftware - Projeção
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            Licenças
                        </a>
                    </li>
                </ul>
            </nav>
            <div class="copyright pull-right">
                &copy;
                <script>document.write(new Date().getFullYear());</script>, desenvolvido pela <i class="fa fa-heart heart"></i> <a href="#">FabricadeSoftware - Projeção</a>
            </div>
        </div>
    </footer>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>







<!------------------------------------------------------------------------------
ALERTA de Cadastro.
-------------------------------------------------------------------------------->
<div class="mostrar" ></div>
<!-- Modal  Login-->
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="loginmodal-container">
            <h1>Faça login na sua conta</h1><br>
            <form method="POST" class="form" action="<?= base_url('') ?>/login/verificar">
                <span class="field">
                    <label for="cpf">Usuario:</label>
                    <input type="text" class="form-cadastro" ng-model="cpf" name="usuario" id="cpf"  placeholder="Usuario">
                    
                </span>
                <span class="field">
                    <label for="psw">Senha:</label>
                    <input type="text" class="form-cadastro" ng-model="psw" name="password" id="psw"  placeholder="Senha">
                    
                </span>
                <input type="submit" name="login" ng-click="Getverificaacesso(cpf, psw);" class="login loginmodal-submit" value="Entrar">
            </form>

            <h1 ng-repeat="x in verifica">{{x.psw}}</h1>
            <span id='labelsenha'>Favor, verifique os dados digitados</span>
            <div class="login-help">
                <a href="#"ng-click="Getmodallogincadastro();">Registro</a> - <a href="#">Esqueceu a senha</a>
            </div>
        </div>
    </div>
</div>


<script>
	$(function(){
		$('.form').submit(function(){
//			$('.loading').html("<img src='loading.gif' width='45'>");
			$.ajax({
				url: '<?=base_url('') ?>/login/verificar',
				type: 'POST',
				data: $('.form').serialize(),
				success: function(data){
					$('.mostrar').html(data);
//					$('.loading').hide();
//					$('.form')[0].reset();
				}
			});
			return true;
		});
	});
</script>	


<!-- Modal cadastro -->
<div class="modal fade" id="cadastro-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="loginmodal-container">
            <h1>Faça seu cadastro</h1><br>

            <form method="POST" enctype="multipart/form-data">
                <span class="field">
                    <input type="text" class="form-cadastro" ng-model="nome" name="nome" id="nome" required placeholder="Nome">
                    <label for="nome">Nome:</label>
                </span>
                <span class="field">
                    <input type="text" class="form-cadastro" ng-model="email" name="email" id="email" required placeholder="E-mail">
                    <label for="email">E-mail:</label>
                </span>
                <span class="field">
                    <input type="text" class="form-cadastro" ng-model="cpf" name="cpf" id="cpf" required placeholder="CPF">
                    <label for="cpf">CPF:</label>
                </span>
                <span class="field">
                    <input type="text" class="form-cadastro" ng-model="psw" name="psw" id="psw" required placeholder="senha">
                    <label for="psw">Senha:</label>
                </span>
                <input type="submit" name="login" class="login loginmodal-submit" ng-click="GetLogin(cpf, nome, email, psw);" value="Cadastrar">
            </form>
            <span id='labelrecuperar'>Desejo recuperar minha senha <a href="#">Clique aqui</a></span>
            <h1 ng-repeat="x in dados"><?php
                $str = '{{x.psw}}';
                echo md5($str)
                ?></h1>
        </div>
    </div>
</div>


<!------------------------------------------------------------------------------
ALERTA de login.
-------------------------------------------------------------------------------->
<!-- Modal -->
<div class="modal fade" id="Cadastro_login" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content col-sm-10 offset-sm-5" style=" width: 70%;    left: 130px;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Logo Loja</h4>
            </div>

            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <br />
                        <p><strong>Novo no site("xxxxxxxx")?</strong></p>
                        <p>Crie uma conta e comece agora.</p>
                        <a href="#" ng-click="Getmodallogincadastro();" class="btn btn-info">Criar uma conta</a>
                        <br /><br />
                    </div>

                    <div class="col-sm-5">
                        <br />
                        <p><strong>Usuários registrados</strong></p>
                        <p>Tem uma conta? Faça login agora.</p>
                        <a href="#" ng-click="Getmodallogin();" class="btn btn-success">Entrar</a>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<!--     Button trigger modal 
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>-->

<!-- Modal orçamento -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Cadastro Orçamento</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">

                    <!-- janela modal Cadastrar Orçamento -->     



                    <div class="col-sm-5">
                        <form method="POST" action="<?= base_url('') ?>/cadastro/orcamento" enctype="multipart/form-data">
                            <div class="form-group">
                                <label for="nome">Nome Completo</label>
                                <input type="text" class="form-control" name="nome" placeholder="José"  required/>
                            </div>
                            <div class="form-group">
                                <label for="nome">Telefone</label>
                                <input type="text" class="form-control" name="telefone" required/>
                            </div>
                            <div class="form-group">
                                <label for="nome">Descrição</label>
                                <textarea  class="form-control rounded-0" rows="4" cols="50" name="descricao">                                        
                                </textarea>
                            </div>
                            <div class="form-group">
                                <label for="nome">Cidade Evento</label>
                                <input type="text" class="form-control" name="cidade"  required/>
                            </div>
                            <div class="form-group" >
                                <label for="nome">Produto</label><br>
                                <select data-placeholder="Choose a Country..." class="select" multiple tabindex="3" name="produto[]" id="sel">
                                    <?php foreach ($this->view->produtos as $produtos) { ?>
                                        <?php echo '<option>' . $produtos['nome'] . '</option>'; ?>                                        
                                    <?php } ?>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="nome">Quantidade</label>
                                <input type="text" class="form-control" name="qtd" required/>
                            </div>
                            <div class="form-group">
                                <label for="nome">Data Evento</label>
                                <input type="date" class="form-control" name="data" required/>
                            </div>
                            <br><br>
                            <input type="submit" value="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Cadastrar &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" class="btn btn-primary btn-lg"/>

                        </form>
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>        
            </div>
        </div>

    </div>
</div>
</div>




