<?php
session_start();

$_SESSION['login'] = "sim";
$_SESSION['modal_aberta'];

//print_r($_SESSION);
?>
<div id="section1" class="container-fluid">
        <div class="col-md-4 offset-md-4">
            <!--<h1>Sessão 1</h1>
            <p>Clique nos diferentes links da Seção na barra de navegação</p>-->
        </div>
    </div>

    <div id="section2" class="container-fluid">
        <center>
            <div class="sectionint">
                <h1>Sessão 2</h1>
                <p>Clique nos diferentes links da Seção na barra de navegação</p>
                <input type="text" class="form-control" ng-model="nome">
                {{nome}}
            </div>
        </center>
    </div>
    <div id="section3" class="container-fluid">
        <center>
            <div class="sectionint">
                <h1>Sessão 3</h1>
                <p>Clique nos diferentes links da Seção na barra de navegação</p>
            </div>
        </center>
    </div>
    <div id="section4" class="container-fluid">
        <center>
            <div class="sectionint">
                <h1>Sessão 4</h1>
                <p>Clique nos diferentes links da Seção na barra de navegação</p>
            </div>
        </center>
    </div>
    <div id="section5" class="container-fluid">
        <center>
            <div class="sectionint">
                <h1>Sessão 5</h1>
                <p>Clique nos diferentes links da Seção na barra de navegação</p>
            </div>
        </center>
    </div>
    <div id="section6" class="container-fluid">
        <center>
            <div class="sectionint">
                <h1>Sessão 6</h1>
                <p>Clique nos diferentes links da Seção na barra de navegação</p>
            </div>
        </center>
    </div>
    <div id="footer">
        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="#">
                                FabricadeSoftware - Projeção
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Licenças
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright pull-right">
                    &copy;
                    <script>document.write(new Date().getFullYear())</script>, desenvolvido pela <i class="fa fa-heart heart"></i> <a href="#">FabricadeSoftware - Projeção</a>
                </div>
            </div>
        </footer>
    </div>
    <!------------------------------------------------------------------------------
        ALERTA de Cadastro.
    -------------------------------------------------------------------------------->
    <!-- Modal cadastro -->
    <div class="modal fade" id="cadastro-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
       <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <div class="modal-dialog">
            
            <div class="loginmodal-container">
                <h1>Faça seu cadastro</h1><br>
                <form action="cadastro/cliente" method="POST">
                    <input type="text" name="nome" placeholder="nome">
                    <input type="text" name="email" placeholder="E-mail">
                    <input type="text" name="telefone" placeholder="Telefone">
                    <input type="text" name="user" placeholder="Usuário">
                    <input type="password" name="password" placeholder="Senha">
                    <input type="password" name="password_repeat" placeholder="Repita a Senha">
                    <input type="submit" id="uploadf" name="cadastrar" class="login loginmodal-submit" value="Cadastrar">
                </form>

            </div>
        </div>
    </div>
    <!------------------------------------------------------------------------------
        ALERTA de login.
    -------------------------------------------------------------------------------->
    <!-- Modal -->
    <div class="modal fade" id="Cadastro_login" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content col-sm-10 offset-sm-5" style=" width: 70%;    left: 130px;">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Logo Loja</h4>
                </div>

                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <br />
                            <p><strong>Novo no site("xxxxxxxx")?</strong></p>
                            <p>Crie uma conta e comece agora.</p>
                            <a href="#" ng-click="Getmodallogincadastro();" class="btn btn-info">Criar uma conta</a>
                            <br /><br />
                        </div>

                        <div class="col-sm-5">
                            <br />
                            <p><strong>Usuários registrados</strong></p>
                            <p>Tem uma conta? Faça login agora.</p>
                            <a href="#" ng-click="Getmodallogin();" class="btn btn-success">Entrar</a>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>
   
