<?php
ini_set('default_charset', 'UTF-8');
ini_set('mssql.charset', 'UTF-8');

if(!isset($_SESSION)) 
    { 
        session_start(); 
        
    }
if(isset($_GET["sair"])){
    echo 'sair';
    session_destroy();
    header('Location:'.base_url('').'/index');
}
?>
<!DOCTYPE html>
<html lang="pt-BR">
<head>
<title>Dashbord | MariathDoces</title>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="<?= base_url('')?>/public/home/css/chosen.css"  />
<link rel="stylesheet" href="<?= base_url('')?>/public/admin/mapes/assets/css/bootstrap.min.css" />
<link rel="stylesheet" href="<?= base_url('')?>/public/admin/css/toastr.css" />
<link rel="stylesheet" href="<?= base_url('')?>/public/admin/mapes/assets/css/bootstrap-responsive.min.css" />
<link rel="stylesheet" href="<?= base_url('')?>/public/admin/mapes/assets/css/matrix-style.css" />
<link rel="stylesheet" href="<?= base_url('')?>/public/admin/mapes/assets/css/matrix-media.css" />
<link rel="stylesheet" href="<?= base_url('')?>/node_modules/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="<?= base_url('')?>/public/admin/mapes/assets/font-awesome/css/font-awesome.css"  />
<link rel="stylesheet" href="<?= base_url('')?>/public/admin/css/style.css">
<link rel="stylesheet" href="<?= base_url('')?>/public/admin/mapes/assets/css/fullcalendar.css" />
<link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,800' >
<!-- Scripts -->
<script src="<?= base_url('')?>/public/admin/mapes/assets/js/jquery-3.3.1.js"></script>
<!--<script type="text/javascript" src="<?= base_url('')?>/public/admin/js/jquery-1.10.2.js"></script>-->

<!--<script type="text/javascript" src="<?= base_url('')?>/public/admin/mapes/assets/js/Chart.min.js"></script>-->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>
<script type="text/javascript" src="<?= base_url('')?>/public/admin/js/jquery.mask.min.js"></script>
<script type="text/javascript" src="<?= base_url('')?>/public/admin/js/jquery.maskMoney.min.js"></script>
<style>
    #alerta{
               margin-left: 75%; 
               position: absolute;
               z-index:1;
               margin-top: 0%; 
               margin-right: 0px;
               border: 1px solid #009688;
               border-radius: 5%;
               font-size: 13px;
               font-weight: bold;
            }
 .container {
        width: 100vw;
        height: 100vh;
        background: rgba(0,0,0,0.50);
        display: none;
        flex-direction: row;
        justify-content: center;
		position:fixed;
		z-index:50;
        align-items: center
    }
    .box {
        width: 80%;
		max-width:700px;
        height: 80%;
		padding:10px;
		overflow:auto;
		border-radius:20px;
        background: #fff;
    }
    #header{
        width: 5%;
    }
    #sidebar{
        margin-top: 2px;
    }
    #content {
        margin-top: 40px;
    }
    .sair{
        font-family: sans-serif,fantasy;
        position: relative;
        margin-top: 1.5%;
          margin-bottom:  0.5%;
        /*float: right;*/
        margin-left:  1100px;
        border-radius: 5%;
        /*//float: right;*/
    }
    
    
    canvas{
			-moz-user-select: none;
			-webkit-user-select: none;
			-ms-user-select: none;
		}
		.chart-container {
			width: 500px;
			margin-left: 40px;
			margin-right: 40px;
			margin-bottom: 40px;
		}
		.grafico {
			display: flex;
			flex-direction: row;
			flex-wrap: wrap;
			justify-content: center;
		}
		.despesa {
			display: flex;
			flex-direction: row;
			flex-wrap: wrap;
			justify-content: center;
		}
</style>
<script  type="text/javascript">

        function pagamento() {
            if (document.getElementById("divPagamentoEditar").style.display == "none")      {
                        document.getElementById("divPagamentoEditar").style.display = "block";      
            }else { 
                        document.getElementById("divPagamentoEditar").style.display = "none";       } 
                    }
    </script>


</head>
<body>

<div class="container" id="notificacao">
        <div class="box" id="notificacaofilho">
        Aguarde...
       </div>
   </div>

 

<!--top-Header-menu-->
 
       
    
      <a title="" href="?sair=Sim"><button type="button" class="btn btn-info sair" ><span class="text">Sair</span></button></a>
 
  
<!--Conteudo-->
        <?php $this->content()?>
<!--Fim Conteudo-->  

<!--Footer-part-->
<div class="row-fluid">
  <div id="footer" class="span12"> 2018 &copy; Fabrica de Software - Projeção / Guara 2</div>
</div>
<!--end-Footer-part-->

<!-- Latest compiled and minified JavaScript -->
<script src="<?= base_url('') ?>/public/home/js/menssagen.js"></script>
<script src="<?= base_url('')?>/public/admin/mapes/assets/js/jquery.validate.js"></script>
<script src="<?= base_url('')?>/public/admin/mapes/assets/js/bootstrap.min.js"></script>
<script src="<?= base_url('')?>/public/admin/js/toastr.js"></script>
<script src="<?= base_url('')?>/public/admin/mapes/assets/js/matrix.js"></script> 


</body>
</html>




