<?php
if(!isset($_SESSION)) 
    { 
        session_start(); 
        
    }
if(isset($_GET["sair"])){
    echo 'sair';
    session_destroy();
    header('Location:'.base_url('').'/index');
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<title>Dashbord | MariathDoces</title>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />


    

<!-- Latest compiled and minified CSS -->

<link href="<?= base_url('')?>/public/home/css/chosen.css" rel="stylesheet" />
<link rel="stylesheet" href="<?= base_url('')?>/public/admin/mapes/assets/css/bootstrap.min.css" />
<link rel="stylesheet" href="<?= base_url('')?>/public/admin/css/toastr.css" />
<link rel="stylesheet" href="<?= base_url('')?>/public/admin/mapes/assets/css/bootstrap-responsive.min.css" />
<link rel="stylesheet" href="<?= base_url('')?>/public/admin/mapes/assets/css/matrix-style.css" />
<link rel="stylesheet" href="<?= base_url('')?>/public/admin/mapes/assets/css/matrix-media.css" />
<link href="<?= base_url('')?>/public/admin/mapes/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
<link rel="stylesheet" href="<?= base_url('')?>/public/admin/mapes/assets/css/fullcalendar.css" /> 

<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>
<script type="text/javascript"  src="<?= base_url('')?>/public/admin/mapes/assets/js/jquery-1.10.2.min.js"></script>
<script src="<?= base_url('')?>/public/js/jquery.mask.min.js"></script>
<script src="<?= base_url('')?>/public/js/jquery.maskMoney.min.js"></script>

<style>
    #alerta{
               display: inline;
               float: right; 
               position: relative;
               margin-top: 40px; 
               margin-right: 20px;
            }
 .container {
        width: 100vw;
        height: 100vh;
        background: rgba(0,0,0,0.50);
        display: none;
        flex-direction: row;
        justify-content: center;
		position:fixed;
		z-index:50;
        align-items: center
    }
    .box {
        width: 80%;
		max-width:700px;
        height: 80%;
		padding:10px;
		overflow:auto;
		border-radius:20px;
        background: #fff;
    }
    #header{
        width: 5%;
    }
    #sidebar{
        margin-top: 63px;
    }
    #content {
        margin-top: 40px;
    }
    .sair{
        font-family: sans-serif,fantasy;
        position: relative;
        margin-top: 1.5%;
          margin-bottom:  0.5%;
        /*float: right;*/
        margin-left:  1100px;
        border-radius: 5%;
        /*//float: right;*/
    }
</style>



</head>
<body>

<div class="container" id="notificacao">
        <div class="box" id="notificacaofilho">
        Aguarde...
       </div>
   </div>

 

<!--top-Header-menu-->
 
       
    
      <a title="" href="?sair=Sim"><button type="button" class="btn btn-info sair" ><span class="text">Sair</span></button></a>
 
  
<!--Conteudo-->
        <?php $this->content()?>
<!--Fim Conteudo-->  

<!--Footer-part-->
<div class="row-fluid">
  <div id="footer" class="span12"> 2018 &copy; Fabrica de Software - Projeção / Guara 2</div>
</div>
<!--end-Footer-part-->

<!-- Latest compiled and minified JavaScript -->
<script src="<?= base_url('')?>/public/admin/mapes/assets/js/bootstrap.min.js"></script>
<script src="<?= base_url('')?>/public/admin/js/toastr.js"></script>
<script src="<?= base_url('')?>/public/admin/mapes/assets/js/matrix.js"></script> 


</body>
</html>




