

<?php
session_start();
?>
<!DOCTYPE html>
<html>
    <head>
        <title><?php echo $this->getPageTitle(" | MariaThDoces") ?></title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Style -- CSS -- LINK -->
        <link rel="stylesheet" href="public/css/bootstrap.min.css">
        <link href="public/css/Script.css" rel="stylesheet" />
        <link href="public/css/bootstrap.css" rel="stylesheet" />      


        <!-- Magnific Popup core CSS file -->
        <link rel="stylesheet" href="<?= base_url('') ?>/public/home/css/magnific-popup.css">



        <!-- Magnific Popup core JS file -->
        <script src="<?= base_url('') ?>/public/home/js/jquery.magnific-popup.js"></script>



        <!-- Script -- JS -- LINK -->
        <script src="public/js/jquery.js"></script>
        <script src="public/js/tether.js"></script>
        <script src="public/js/angular.js"></script>
        <script src="public/js/script.js"></script>
        <script src="public/js/bootstrap.min.js"></script>
        <script src="public/js/jquery.mask.min.js"></script>

        <link rel="shortcut icon" href="<?= base_url('') ?>/public/img/Maria_Doces-icones-01.png" type="image/text" >
        <link rel="stylesheet" href="<?= base_url('') ?>/public/home/css/bootstrap.min.css">
        <link href="<?= base_url('') ?>/public/home/css/chosen.css" rel="stylesheet" />
        <link href="<?= base_url('') ?>/public/home/css/all.css" rel="stylesheet" />  
      

        <script src="<?= base_url('') ?>/public/js/sweetalert2.js"></script>
        

        <script src="<?= base_url('') ?>/public/home/js/chosen.jquery.js"></script>
        <script src="<?= base_url('') ?>/public/home/js/all.js"></script>
        <script src="<?= base_url('') ?>/public/home/js/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>


        <script type="text/javascript">
$(document).ready(function() {
$('#open-popup').magnificPopup({
    items: [
      {
        src: '<?= base_url('') ?>/public/img/galeria/img1.jpg',
        title: 'Peter & Paul fortress in SPB'
      },
      {
        src: 'https://vimeo.com/123123',
        type: 'iframe' // this overrides default type
      },
      {
        src: $('<div class="white-popup">Dynamically created element</div>'), // Dynamically created element
        type: 'inline'
      },
      {
        src: '<div class="white-popup">Popup from HTML string</div>', // HTML string
        type: 'inline'
      },
      {
        src: '#my-popup', // CSS selector of an element on page that should be used as a popup
        type: 'inline'
      }
    ],
    gallery: {
      enabled: true
    },
    type: 'image' // this is a default type
});

});
</script>

<style>
  #open-popup {padding:20px}
.white-popup {
  position: relative;
  background: #FFF;
  padding: 40px;
  width: auto;
  max-width: 200px;
  margin: 20px auto;
  text-align: center;
}  
    
/* padding-bottom and top for image 
.mfp-no-margins img.mfp-img {
padding: 0;
}
 position of shadow behind the image 
.mfp-no-margins .mfp-figure:after {
top: 0;
bottom: 0;
}
 padding for main container 
.mfp-no-margins .mfp-container {
padding: 0;
}


 

for zoom animation 
uncomment this part if you haven't added this code anywhere else




.mfp-with-zoom .mfp-container,
.mfp-with-zoom.mfp-bg {
opacity: 0;
-webkit-backface-visibility: hidden;
-webkit-transition: all 0.3s ease-out; 
-moz-transition: all 0.3s ease-out; 
-o-transition: all 0.3s ease-out; 
transition: all 0.3s ease-out;
}

.mfp-with-zoom.mfp-ready .mfp-container {
	opacity: 1;
}
.mfp-with-zoom.mfp-ready.mfp-bg {
	opacity: 0.8;
}

.mfp-with-zoom.mfp-removing .mfp-container, 
.mfp-with-zoom.mfp-removing.mfp-bg {
opacity: 0;
}*/

</style>



    </head >
    <body ng-app="sistema" ng-controller="SistemaCtrl" ng-init="FnInit();" >

        <nav class="navbar navbar-inverse navbar-fixed-top bg-dark">

            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <img id="logo-home" src="<?= base_url('') ?>/public/img/Maria_Doces_4.png" onclick="rolar_para('#section1')">
                </div>

                <div>
                    <div class="collapse navbar-collapse" id="myNavbar">
                        <ul class="nav navbar-nav" style="float:right;">
                            <li class="nav-item active"><a href="#" onclick="rolar_para('#section1')">Menu</a></li>                        
                            <li><a href="#" onclick="rolar_para('#section2')">Sobre Nós</a></li>
                            <li><a class="dropdown-toggle" href="#" onclick="rolar_para('#section3')">Serviços</a></li>
                            <li><a class="dropdown-toggle" href="#" onclick="rolar_para('#section4')">Orçamento</a></li>
                            <li><a class="dropdown-toggle" href="#" onclick="rolar_para('#section5')">Galeria</a></li>
                            <li><a href="#" ng-click="Getmodalcadastro();">Login | Cadastro</a></li>
                            <li><a href="#section4" onclick="rolar_para('#section6')">Contato</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
        <ul class="cb-slideshow">
            <li class="li"><span></span><div><h3>Slide1</h3>Texto1</div></li>
            <li class="li"><span></span><div><h3>Slide2</h3>Texto2</div></li>
            <li class="li"><span></span><div><h3>Slide3</h3>Texto3</div></li>
            <li class="li"><span></span><div><h3>Slide4</h3>Texto4</div></li>
            <li class="li"><span></span><div><h3>Slide5</h3>Texto5</div></li>
            <li class="li"><span></span><div><h3>Slide6</h3>Texto6</div></li>
        </ul>
        <!--Conteudo-->
        <?php $this->content() ?>
        <!--Fim Conteudo-->


        <script>
                    $(document).ready(function () {
                        $('#sel').chosen();


                    });
        </script>
    </body>
</html>
