<?php
if(!isset($_SESSION)) 
    { 
        session_start(); 
        
    }

if(isset($_SESSION['sucess'])){
    echo $_SESSION['sucess']; 
   unset($_SESSION['sucess']);
}

if($_SESSION['authenticado'] === TRUE){
    echo 'Autenticado';
} else {
    header("Location:".base_url('')."/index");
}

if (isset($_GET['sair']) == 'sim') {
    session_destroy();
    session_unset();
    header("Location:" . base_url("") . "/index");
}
?>


﻿<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="/admin/img/apple-icon.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/admin/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>PFabrica de Software</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Bootstrap core CSS     -->
    <link href="public/admin/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Animation library for notifications   -->
    <link href="public/admin/css/animate.min.css" rel="stylesheet" />
    <!--  Paper Dashboard core CSS    -->
    <link href="public/admin/css/paper-dashboard.css" rel="stylesheet" />
    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="public/admin/css/demo.css" rel="stylesheet" />
    <!--  icons     -->
    <link href="public/admin/css/themify-icons.css" rel="stylesheet">
    <!-- Angular -->
    <script src="public/admin/scripts/angular.js"></script>
    <script src="public/admin/scripts/Script.js"></script>
</head>
<body ng-app="meuapp" ng-controller="meuappCtrl" ng-init="FnInit();">
        <!--Conteudo-->
        <?php $this->content()?>
        
        <!--Fim Conteudo-->        
    </body>
<!--   Core JS Files   -->
<script src="public/admin/js/jquery-1.10.2.js" type="text/javascript"></script>
<script src="public/admin/js/bootstrap.min.js" type="text/javascript"></script>
<!--  Checkbox, Radio & Switch Plugins -->
<script src="public/admin/js/bootstrap-checkbox-radio.js"></script>
<!--  Charts Plugin -->
<script src="public/admin/js/chartist.min.js"></script>
<!--  Notifications Plugin    -->
<script src="public/admin/js/bootstrap-notify.js"></script>
<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>
<!-- Paper Dashboard Core javascript and methods for Demo purpose -->
<script src="public/admin/js/paper-dashboard.js"></script>
<!-- Paper Dashboard DEMO methods, don't include it in your project! -->
<script src="public/admin/js/demo.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        demo.initChartist();

        $.notify({
            icon: 'ti-gift',
            message: "Bem Vindo <b>Nome Usuário</b>"

        }, {
            type: 'success',
            timer: 4000
        });

    });
</script>
</html>
